/*
This is the migration script to update the database with the set of uncommitted changes you selected.

You can customize the script, and your edits will be used in deployment.
The following objects will be affected:
  dbo.HVLog, dbo.spAddHVLog, dbo.spEditHVLog
*/

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping foreign keys from [dbo].[HVLog]'
GO
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT[FK_HVLog_FSWFK]
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT[FK_HVLog_HVCaseFK]
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT[FK_HVLog_NonPrimaryFSWFK]
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT[FK_HVLog_ProgramFK]
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT[FK_HVLog_FatherAdvocateFK]
GO
PRINT N'Dropping constraints from [dbo].[HVLog]'
GO
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT [PK__HVLog__ED876F581332DBDC]
GO
PRINT N'Dropping constraints from [dbo].[HVLog]'
GO
ALTER TABLE [dbo].[HVLog] DROP CONSTRAINT [DF_HVLog_HVLogCreateDate]
GO
PRINT N'Rebuilding [dbo].[HVLog]'
GO
CREATE TABLE [dbo].[tmp_rg_xx_HVLog]
(
[HVLogPK] [int] NOT NULL IDENTITY(1, 1),
[CAChildSupport] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAAdvocacy] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAGoods] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAHousing] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALaborSupport] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALegal] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAParentRights] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATranslation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATransportation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAVisitation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDChildDevelopment] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDToys] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIProblems] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIOtherSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Curriculum247Dads] [bit] NULL,
[CurriculumBoyz2Dads] [bit] NULL,
[CurriculumGrowingGreatKids] [bit] NULL,
[CurriculumHelpingBabiesLearn] [bit] NULL,
[CurriculumInsideOutDads] [bit] NULL,
[CurriculumMomGateway] [bit] NULL,
[CurriculumOther] [bit] NULL,
[CurriculumOtherSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurriculumParentsForLearning] [bit] NULL,
[CurriculumPartnersHealthyBaby] [bit] NULL,
[CurriculumPAT] [bit] NULL,
[CurriculumPATFocusFathers] [bit] NULL,
[CurriculumSanAngelo] [bit] NULL,
[FatherAdvocateFK] [int] NULL,
[FatherAdvocateParticipated] [bit] NULL,
[FatherFigureParticipated] [bit] NULL,
[FFCommunication] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFDomesticViolence] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFFamilyRelations] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFMentalHealth] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FFSubstanceAbuse] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSWFK] [int] NULL,
[GrandParentParticipated] [bit] NULL,
[HCBreastFeeding] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCChild] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCDental] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCFamilyPlanning] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCFASD] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCFeeding] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCGeneral] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCMedicalAdvocacy] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCNutrition] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCPrenatalCare] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCProviders] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCSafety] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCSexEducation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCSIDS] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCSmoking] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVCaseFK] [int] NOT NULL,
[HVLogCreateDate] [datetime] NOT NULL CONSTRAINT [DF_HVLog_HVLogCreateDate] DEFAULT (getdate()),
[HVLogCreator] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HVLogEditDate] [datetime] NULL,
[HVLogEditor] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVSupervisorParticipated] [bit] NULL,
[NonPrimaryFSWParticipated] [bit] NULL,
[NonPrimaryFSWFK] [int] NULL,
[OBPParticipated] [bit] NULL,
[OtherLocationSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherParticipated] [bit] NULL,
[PAAssessmentIssues] [bit] NULL,
[PAForms] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAGroups] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAIFSP] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARecreation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PASpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAVideo] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentCompletedActivity] [bit] NULL,
[ParentObservationsDiscussed] [bit] NULL,
[ParticipatedSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1Participated] [bit] NULL,
[PC2Participated] [bit] NULL,
[PCBasicNeeds] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCChildInteraction] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCChildManagement] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCFeelings] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCShakenBaby] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCShakenBabyVideo] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCStress] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramFK] [int] NULL,
[ReviewAssessmentIssues] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiblingParticipated] [bit] NULL,
[SSCalendar] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSChildCare] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSEducation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSEmployment] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSHousekeeping] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSJob] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSMoneyManagement] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSOther] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSProblemSolving] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSTransportation] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorObservation] [bit] NULL,
[TCParticipated] [bit] NULL,
[TotalPercentageSpent] [int] NULL,
[UpcomingProgramEvents] [bit] NULL,
[VisitLengthHour] [int] NOT NULL,
[VisitLengthMinute] [int] NOT NULL,
[VisitLocation] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VisitStartTime] [datetime] NOT NULL,
[VisitType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tmp_rg_xx_HVLog] ON
GO
INSERT INTO [dbo].[tmp_rg_xx_HVLog]([HVLogPK], [CAChildSupport], [CAAdvocacy], [CAGoods], [CAHousing], [CALaborSupport], [CALegal], [CAOther], [CAParentRights], [CASpecify], [CATranslation], [CATransportation], [CAVisitation], [CDChildDevelopment], [CDOther], [CDSpecify], [CDToys], [CIProblems], [CIOther], [CIOtherSpecify], [Curriculum247Dads], [CurriculumBoyz2Dads], [CurriculumGrowingGreatKids], [CurriculumHelpingBabiesLearn], [CurriculumInsideOutDads], [CurriculumMomGateway], [CurriculumOther], [CurriculumOtherSpecify], [CurriculumParentsForLearning], [CurriculumPartnersHealthyBaby], [CurriculumPAT], [CurriculumPATFocusFathers], [CurriculumSanAngelo], [FatherAdvocateFK], [FatherAdvocateParticipated], [FatherFigureParticipated], [FFCommunication], [FFDomesticViolence], [FFFamilyRelations], [FFMentalHealth], [FFOther], [FFSpecify], [FFSubstanceAbuse], [FSWFK], [GrandParentParticipated], [HCBreastFeeding], [HCChild], [HCDental], [HCFamilyPlanning], [HCFASD], [HCFeeding], [HCGeneral], [HCMedicalAdvocacy], [HCNutrition], [HCOther], [HCPrenatalCare], [HCProviders], [HCSafety], [HCSexEducation], [HCSIDS], [HCSmoking], [HCSpecify], [HVCaseFK], [HVLogCreateDate], [HVLogCreator], [HVLogEditDate], [HVLogEditor], [HVSupervisorParticipated], [NonPrimaryFSWParticipated], [NonPrimaryFSWFK], [OBPParticipated], [OtherLocationSpecify], [OtherParticipated], [PAAssessmentIssues], [PAForms], [PAGroups], [PAIFSP], [PAOther], [PARecreation], [PASpecify], [PAVideo], [ParentCompletedActivity], [ParentObservationsDiscussed], [ParticipatedSpecify], [PC1Participated], [PC2Participated], [PCBasicNeeds], [PCChildInteraction], [PCChildManagement], [PCFeelings], [PCOther], [PCShakenBaby], [PCShakenBabyVideo], [PCSpecify], [PCStress], [ProgramFK], [ReviewAssessmentIssues], [SiblingParticipated], [SSCalendar], [SSChildCare], [SSEducation], [SSEmployment], [SSHousekeeping], [SSJob], [SSMoneyManagement], [SSOther], [SSProblemSolving], [SSSpecify], [SSTransportation], [SupervisorObservation], [TCParticipated], [TotalPercentageSpent], [UpcomingProgramEvents], [VisitLengthHour], [VisitLengthMinute], [VisitLocation], [VisitStartTime], [VisitType]) SELECT [HVLogPK], [CAChildSupport], [CAAdvocacy], [CAGoods], [CAHousing], [CALaborSupport], [CALegal], [CAOther], [CAParentRights], [CASpecify], [CATranslation], [CATransportation], [CAVisitation], [CDChildDevelopment], [CDOther], [CDSpecify], [CDToys], [CIProblems], [CIOther], [CIOtherSpecify], [Curriculum247Dads], [CurriculumBoyz2Dads], [CurriculumGrowingGreatKids], [CurriculumHelpingBabiesLearn], [CurriculumInsideOutDads], [CurriculumMomGateway], [CurriculumOther], [CurriculumOtherSpecify], [CurriculumParentsForLearning], [CurriculumPartnersHealthyBaby], [CurriculumPAT], [CurriculumPATFocusFathers], [CurriculumSanAngelo], [FatherAdvocateFK], [FatherAdvocateParticipated], [FatherFigureParticipated], [FFCommunication], [FFDomesticViolence], [FFFamilyRelations], [FFMentalHealth], [FFOther], [FFSpecify], [FFSubstanceAbuse], [FSWFK], [GrandParentParticipated], [HCBreastFeeding], [HCChild], [HCDental], [HCFamilyPlanning], [HCFASD], [HCFeeding], [HCGeneral], [HCMedicalAdvocacy], [HCNutrition], [HCOther], [HCPrenatalCare], [HCProviders], [HCSafety], [HCSexEducation], [HCSIDS], [HCSmoking], [HCSpecify], [HVCaseFK], [HVLogCreateDate], [HVLogCreator], [HVLogEditDate], [HVLogEditor], [HVSupervisorParticipated], [NonPrimaryFSWParticipated], [NonPrimaryFSWFK], [OBPParticipated], [OtherLocationSpecify], [OtherParticipated], [PAAssessmentIssues], [PAForms], [PAGroups], [PAIFSP], [PAOther], [PARecreation], [PASpecify], [PAVideo], [ParentCompletedActivity], [ParentObservationsDiscussed], [ParticipatedSpecify], [PC1Participated], [PC2Participated], [PCBasicNeeds], [PCChildInteraction], [PCChildManagement], [PCFeelings], [PCOther], [PCShakenBaby], [PCShakenBabyVideo], [PCSpecify], [PCStress], [ProgramFK], [ReviewAssessmentIssues], [SiblingParticipated], [SSCalendar], [SSChildCare], [SSEducation], [SSEmployment], [SSHousekeeping], [SSJob], [SSMoneyManagement], [SSOther], [SSProblemSolving], [SSSpecify], [SSTransportation], [SupervisorObservation], [TCParticipated], [TotalPercentageSpent], [UpcomingProgramEvents], [VisitLengthHour], [VisitLengthMinute], [VisitLocation], [VisitStartTime], [VisitType] FROM [dbo].[HVLog]
GO
SET IDENTITY_INSERT [dbo].[tmp_rg_xx_HVLog] OFF
GO
DECLARE @idVal BIGINT
SELECT @idVal = IDENT_CURRENT(N'[dbo].[HVLog]')
IF @idVal IS NOT NULL
    DBCC CHECKIDENT(N'[dbo].[tmp_rg_xx_HVLog]', RESEED, @idVal)
GO
DROP TABLE [dbo].[HVLog]
GO
EXEC sp_rename N'[dbo].[tmp_rg_xx_HVLog]', N'HVLog'
GO
PRINT N'Creating primary key [PK__HVLog__ED876F581332DBDC] on [dbo].[HVLog]'
GO
ALTER TABLE [dbo].[HVLog] ADD CONSTRAINT [PK__HVLog__ED876F581332DBDC] PRIMARY KEY CLUSTERED  ([HVLogPK]) ON [PRIMARY]
GO
PRINT N'Altering [dbo].[spAddHVLog]'
GO
ALTER PROCEDURE [dbo].[spAddHVLog](@CAChildSupport char(2)=NULL,
@CAAdvocacy char(2)=NULL,
@CAGoods char(2)=NULL,
@CAHousing char(2)=NULL,
@CALaborSupport char(2)=NULL,
@CALegal char(2)=NULL,
@CAOther char(2)=NULL,
@CAParentRights char(2)=NULL,
@CASpecify varchar(500)=NULL,
@CATranslation char(2)=NULL,
@CATransportation char(2)=NULL,
@CAVisitation char(2)=NULL,
@CDChildDevelopment char(2)=NULL,
@CDOther char(2)=NULL,
@CDSpecify varchar(500)=NULL,
@CDToys char(2)=NULL,
@CIProblems char(2)=NULL,
@CIOther char(2)=NULL,
@CIOtherSpecify varchar(500)=NULL,
@Curriculum247Dads bit=NULL,
@CurriculumBoyz2Dads bit=NULL,
@CurriculumGrowingGreatKids bit=NULL,
@CurriculumHelpingBabiesLearn bit=NULL,
@CurriculumInsideOutDads bit=NULL,
@CurriculumMomGateway bit=NULL,
@CurriculumOther bit=NULL,
@CurriculumOtherSpecify varchar(500)=NULL,
@CurriculumParentsForLearning bit=NULL,
@CurriculumPartnersHealthyBaby bit=NULL,
@CurriculumPAT bit=NULL,
@CurriculumPATFocusFathers bit=NULL,
@CurriculumSanAngelo bit=NULL,
@FatherAdvocateFK int=NULL,
@FatherAdvocateParticipated bit=NULL,
@FatherFigureParticipated bit=NULL,
@FFCommunication char(2)=NULL,
@FFDomesticViolence char(2)=NULL,
@FFFamilyRelations char(2)=NULL,
@FFMentalHealth char(2)=NULL,
@FFOther char(2)=NULL,
@FFSpecify varchar(500)=NULL,
@FFSubstanceAbuse char(2)=NULL,
@FSWFK int=NULL,
@GrandParentParticipated bit=NULL,
@HCBreastFeeding char(2)=NULL,
@HCChild char(2)=NULL,
@HCDental char(2)=NULL,
@HCFamilyPlanning char(2)=NULL,
@HCFASD char(2)=NULL,
@HCFeeding char(2)=NULL,
@HCGeneral char(2)=NULL,
@HCMedicalAdvocacy char(2)=NULL,
@HCNutrition char(2)=NULL,
@HCOther char(2)=NULL,
@HCPrenatalCare char(2)=NULL,
@HCProviders char(2)=NULL,
@HCSafety char(2)=NULL,
@HCSexEducation char(2)=NULL,
@HCSIDS char(2)=NULL,
@HCSmoking char(2)=NULL,
@HCSpecify varchar(500)=NULL,
@HVCaseFK int=NULL,
@HVLogCreator char(10)=NULL,
@HVSupervisorParticipated bit=NULL,
@NonPrimaryFSWParticipated bit=NULL,
@NonPrimaryFSWFK int=NULL,
@OBPParticipated bit=NULL,
@OtherLocationSpecify varchar(500)=NULL,
@OtherParticipated bit=NULL,
@PAAssessmentIssues bit=NULL,
@PAForms char(2)=NULL,
@PAGroups char(2)=NULL,
@PAIFSP char(2)=NULL,
@PAOther char(2)=NULL,
@PARecreation char(2)=NULL,
@PASpecify varchar(500)=NULL,
@PAVideo char(2)=NULL,
@ParentCompletedActivity bit=NULL,
@ParentObservationsDiscussed bit=NULL,
@ParticipatedSpecify varchar(500)=NULL,
@PC1Participated bit=NULL,
@PC2Participated bit=NULL,
@PCBasicNeeds char(2)=NULL,
@PCChildInteraction char(2)=NULL,
@PCChildManagement char(2)=NULL,
@PCFeelings char(2)=NULL,
@PCOther char(2)=NULL,
@PCShakenBaby char(2)=NULL,
@PCShakenBabyVideo char(2)=NULL,
@PCSpecify varchar(500)=NULL,
@PCStress char(2)=NULL,
@ProgramFK int=NULL,
@ReviewAssessmentIssues varchar(500)=NULL,
@SiblingParticipated bit=NULL,
@SSCalendar char(2)=NULL,
@SSChildCare char(2)=NULL,
@SSEducation char(2)=NULL,
@SSEmployment char(2)=NULL,
@SSHousekeeping char(2)=NULL,
@SSJob char(2)=NULL,
@SSMoneyManagement char(2)=NULL,
@SSOther char(2)=NULL,
@SSProblemSolving char(2)=NULL,
@SSSpecify varchar(500)=NULL,
@SSTransportation char(2)=NULL,
@SupervisorObservation bit=NULL,
@TCParticipated bit=NULL,
@TotalPercentageSpent int=NULL,
@UpcomingProgramEvents bit=NULL,
@VisitLengthHour int=NULL,
@VisitLengthMinute int=NULL,
@VisitLocation char(5)=NULL,
@VisitStartTime datetime=NULL,
@VisitType char(4)=NULL)
AS
INSERT INTO HVLog(
CAChildSupport,
CAAdvocacy,
CAGoods,
CAHousing,
CALaborSupport,
CALegal,
CAOther,
CAParentRights,
CASpecify,
CATranslation,
CATransportation,
CAVisitation,
CDChildDevelopment,
CDOther,
CDSpecify,
CDToys,
CIProblems,
CIOther,
CIOtherSpecify,
Curriculum247Dads,
CurriculumBoyz2Dads,
CurriculumGrowingGreatKids,
CurriculumHelpingBabiesLearn,
CurriculumInsideOutDads,
CurriculumMomGateway,
CurriculumOther,
CurriculumOtherSpecify,
CurriculumParentsForLearning,
CurriculumPartnersHealthyBaby,
CurriculumPAT,
CurriculumPATFocusFathers,
CurriculumSanAngelo,
FatherAdvocateFK,
FatherAdvocateParticipated,
FatherFigureParticipated,
FFCommunication,
FFDomesticViolence,
FFFamilyRelations,
FFMentalHealth,
FFOther,
FFSpecify,
FFSubstanceAbuse,
FSWFK,
GrandParentParticipated,
HCBreastFeeding,
HCChild,
HCDental,
HCFamilyPlanning,
HCFASD,
HCFeeding,
HCGeneral,
HCMedicalAdvocacy,
HCNutrition,
HCOther,
HCPrenatalCare,
HCProviders,
HCSafety,
HCSexEducation,
HCSIDS,
HCSmoking,
HCSpecify,
HVCaseFK,
HVLogCreator,
HVSupervisorParticipated,
NonPrimaryFSWParticipated,
NonPrimaryFSWFK,
OBPParticipated,
OtherLocationSpecify,
OtherParticipated,
PAAssessmentIssues,
PAForms,
PAGroups,
PAIFSP,
PAOther,
PARecreation,
PASpecify,
PAVideo,
ParentCompletedActivity,
ParentObservationsDiscussed,
ParticipatedSpecify,
PC1Participated,
PC2Participated,
PCBasicNeeds,
PCChildInteraction,
PCChildManagement,
PCFeelings,
PCOther,
PCShakenBaby,
PCShakenBabyVideo,
PCSpecify,
PCStress,
ProgramFK,
ReviewAssessmentIssues,
SiblingParticipated,
SSCalendar,
SSChildCare,
SSEducation,
SSEmployment,
SSHousekeeping,
SSJob,
SSMoneyManagement,
SSOther,
SSProblemSolving,
SSSpecify,
SSTransportation,
SupervisorObservation,
TCParticipated,
TotalPercentageSpent,
UpcomingProgramEvents,
VisitLengthHour,
VisitLengthMinute,
VisitLocation,
VisitStartTime,
VisitType
)
VALUES(
@CAChildSupport,
@CAAdvocacy,
@CAGoods,
@CAHousing,
@CALaborSupport,
@CALegal,
@CAOther,
@CAParentRights,
@CASpecify,
@CATranslation,
@CATransportation,
@CAVisitation,
@CDChildDevelopment,
@CDOther,
@CDSpecify,
@CDToys,
@CIProblems,
@CIOther,
@CIOtherSpecify,
@Curriculum247Dads,
@CurriculumBoyz2Dads,
@CurriculumGrowingGreatKids,
@CurriculumHelpingBabiesLearn,
@CurriculumInsideOutDads,
@CurriculumMomGateway,
@CurriculumOther,
@CurriculumOtherSpecify,
@CurriculumParentsForLearning,
@CurriculumPartnersHealthyBaby,
@CurriculumPAT,
@CurriculumPATFocusFathers,
@CurriculumSanAngelo,
@FatherAdvocateFK,
@FatherAdvocateParticipated,
@FatherFigureParticipated,
@FFCommunication,
@FFDomesticViolence,
@FFFamilyRelations,
@FFMentalHealth,
@FFOther,
@FFSpecify,
@FFSubstanceAbuse,
@FSWFK,
@GrandParentParticipated,
@HCBreastFeeding,
@HCChild,
@HCDental,
@HCFamilyPlanning,
@HCFASD,
@HCFeeding,
@HCGeneral,
@HCMedicalAdvocacy,
@HCNutrition,
@HCOther,
@HCPrenatalCare,
@HCProviders,
@HCSafety,
@HCSexEducation,
@HCSIDS,
@HCSmoking,
@HCSpecify,
@HVCaseFK,
@HVLogCreator,
@HVSupervisorParticipated,
@NonPrimaryFSWParticipated,
@NonPrimaryFSWFK,
@OBPParticipated,
@OtherLocationSpecify,
@OtherParticipated,
@PAAssessmentIssues,
@PAForms,
@PAGroups,
@PAIFSP,
@PAOther,
@PARecreation,
@PASpecify,
@PAVideo,
@ParentCompletedActivity,
@ParentObservationsDiscussed,
@ParticipatedSpecify,
@PC1Participated,
@PC2Participated,
@PCBasicNeeds,
@PCChildInteraction,
@PCChildManagement,
@PCFeelings,
@PCOther,
@PCShakenBaby,
@PCShakenBabyVideo,
@PCSpecify,
@PCStress,
@ProgramFK,
@ReviewAssessmentIssues,
@SiblingParticipated,
@SSCalendar,
@SSChildCare,
@SSEducation,
@SSEmployment,
@SSHousekeeping,
@SSJob,
@SSMoneyManagement,
@SSOther,
@SSProblemSolving,
@SSSpecify,
@SSTransportation,
@SupervisorObservation,
@TCParticipated,
@TotalPercentageSpent,
@UpcomingProgramEvents,
@VisitLengthHour,
@VisitLengthMinute,
@VisitLocation,
@VisitStartTime,
@VisitType
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
PRINT N'Altering [dbo].[spEditHVLog]'
GO
ALTER PROCEDURE [dbo].[spEditHVLog](@HVLogPK int=NULL,
@CAChildSupport char(2)=NULL,
@CAAdvocacy char(2)=NULL,
@CAGoods char(2)=NULL,
@CAHousing char(2)=NULL,
@CALaborSupport char(2)=NULL,
@CALegal char(2)=NULL,
@CAOther char(2)=NULL,
@CAParentRights char(2)=NULL,
@CASpecify varchar(500)=NULL,
@CATranslation char(2)=NULL,
@CATransportation char(2)=NULL,
@CAVisitation char(2)=NULL,
@CDChildDevelopment char(2)=NULL,
@CDOther char(2)=NULL,
@CDSpecify varchar(500)=NULL,
@CDToys char(2)=NULL,
@CIProblems char(2)=NULL,
@CIOther char(2)=NULL,
@CIOtherSpecify varchar(500)=NULL,
@Curriculum247Dads bit=NULL,
@CurriculumBoyz2Dads bit=NULL,
@CurriculumGrowingGreatKids bit=NULL,
@CurriculumHelpingBabiesLearn bit=NULL,
@CurriculumInsideOutDads bit=NULL,
@CurriculumMomGateway bit=NULL,
@CurriculumOther bit=NULL,
@CurriculumOtherSpecify varchar(500)=NULL,
@CurriculumParentsForLearning bit=NULL,
@CurriculumPartnersHealthyBaby bit=NULL,
@CurriculumPAT bit=NULL,
@CurriculumPATFocusFathers bit=NULL,
@CurriculumSanAngelo bit=NULL,
@FatherAdvocateFK int=NULL,
@FatherAdvocateParticipated bit=NULL,
@FatherFigureParticipated bit=NULL,
@FFCommunication char(2)=NULL,
@FFDomesticViolence char(2)=NULL,
@FFFamilyRelations char(2)=NULL,
@FFMentalHealth char(2)=NULL,
@FFOther char(2)=NULL,
@FFSpecify varchar(500)=NULL,
@FFSubstanceAbuse char(2)=NULL,
@FSWFK int=NULL,
@GrandParentParticipated bit=NULL,
@HCBreastFeeding char(2)=NULL,
@HCChild char(2)=NULL,
@HCDental char(2)=NULL,
@HCFamilyPlanning char(2)=NULL,
@HCFASD char(2)=NULL,
@HCFeeding char(2)=NULL,
@HCGeneral char(2)=NULL,
@HCMedicalAdvocacy char(2)=NULL,
@HCNutrition char(2)=NULL,
@HCOther char(2)=NULL,
@HCPrenatalCare char(2)=NULL,
@HCProviders char(2)=NULL,
@HCSafety char(2)=NULL,
@HCSexEducation char(2)=NULL,
@HCSIDS char(2)=NULL,
@HCSmoking char(2)=NULL,
@HCSpecify varchar(500)=NULL,
@HVCaseFK int=NULL,
@HVLogEditor char(10)=NULL,
@HVSupervisorParticipated bit=NULL,
@NonPrimaryFSWParticipated bit=NULL,
@NonPrimaryFSWFK int=NULL,
@OBPParticipated bit=NULL,
@OtherLocationSpecify varchar(500)=NULL,
@OtherParticipated bit=NULL,
@PAAssessmentIssues bit=NULL,
@PAForms char(2)=NULL,
@PAGroups char(2)=NULL,
@PAIFSP char(2)=NULL,
@PAOther char(2)=NULL,
@PARecreation char(2)=NULL,
@PASpecify varchar(500)=NULL,
@PAVideo char(2)=NULL,
@ParentCompletedActivity bit=NULL,
@ParentObservationsDiscussed bit=NULL,
@ParticipatedSpecify varchar(500)=NULL,
@PC1Participated bit=NULL,
@PC2Participated bit=NULL,
@PCBasicNeeds char(2)=NULL,
@PCChildInteraction char(2)=NULL,
@PCChildManagement char(2)=NULL,
@PCFeelings char(2)=NULL,
@PCOther char(2)=NULL,
@PCShakenBaby char(2)=NULL,
@PCShakenBabyVideo char(2)=NULL,
@PCSpecify varchar(500)=NULL,
@PCStress char(2)=NULL,
@ProgramFK int=NULL,
@ReviewAssessmentIssues varchar(500)=NULL,
@SiblingParticipated bit=NULL,
@SSCalendar char(2)=NULL,
@SSChildCare char(2)=NULL,
@SSEducation char(2)=NULL,
@SSEmployment char(2)=NULL,
@SSHousekeeping char(2)=NULL,
@SSJob char(2)=NULL,
@SSMoneyManagement char(2)=NULL,
@SSOther char(2)=NULL,
@SSProblemSolving char(2)=NULL,
@SSSpecify varchar(500)=NULL,
@SSTransportation char(2)=NULL,
@SupervisorObservation bit=NULL,
@TCParticipated bit=NULL,
@TotalPercentageSpent int=NULL,
@UpcomingProgramEvents bit=NULL,
@VisitLengthHour int=NULL,
@VisitLengthMinute int=NULL,
@VisitLocation char(5)=NULL,
@VisitStartTime datetime=NULL,
@VisitType char(4)=NULL)
AS
UPDATE HVLog
SET 
CAChildSupport = @CAChildSupport, 
CAAdvocacy = @CAAdvocacy, 
CAGoods = @CAGoods, 
CAHousing = @CAHousing, 
CALaborSupport = @CALaborSupport, 
CALegal = @CALegal, 
CAOther = @CAOther, 
CAParentRights = @CAParentRights, 
CASpecify = @CASpecify, 
CATranslation = @CATranslation, 
CATransportation = @CATransportation, 
CAVisitation = @CAVisitation, 
CDChildDevelopment = @CDChildDevelopment, 
CDOther = @CDOther, 
CDSpecify = @CDSpecify, 
CDToys = @CDToys, 
CIProblems = @CIProblems, 
CIOther = @CIOther, 
CIOtherSpecify = @CIOtherSpecify, 
Curriculum247Dads = @Curriculum247Dads, 
CurriculumBoyz2Dads = @CurriculumBoyz2Dads, 
CurriculumGrowingGreatKids = @CurriculumGrowingGreatKids, 
CurriculumHelpingBabiesLearn = @CurriculumHelpingBabiesLearn, 
CurriculumInsideOutDads = @CurriculumInsideOutDads, 
CurriculumMomGateway = @CurriculumMomGateway, 
CurriculumOther = @CurriculumOther, 
CurriculumOtherSpecify = @CurriculumOtherSpecify, 
CurriculumParentsForLearning = @CurriculumParentsForLearning, 
CurriculumPartnersHealthyBaby = @CurriculumPartnersHealthyBaby, 
CurriculumPAT = @CurriculumPAT, 
CurriculumPATFocusFathers = @CurriculumPATFocusFathers, 
CurriculumSanAngelo = @CurriculumSanAngelo, 
FatherAdvocateFK = @FatherAdvocateFK, 
FatherAdvocateParticipated = @FatherAdvocateParticipated, 
FatherFigureParticipated = @FatherFigureParticipated, 
FFCommunication = @FFCommunication, 
FFDomesticViolence = @FFDomesticViolence, 
FFFamilyRelations = @FFFamilyRelations, 
FFMentalHealth = @FFMentalHealth, 
FFOther = @FFOther, 
FFSpecify = @FFSpecify, 
FFSubstanceAbuse = @FFSubstanceAbuse, 
FSWFK = @FSWFK, 
GrandParentParticipated = @GrandParentParticipated, 
HCBreastFeeding = @HCBreastFeeding, 
HCChild = @HCChild, 
HCDental = @HCDental, 
HCFamilyPlanning = @HCFamilyPlanning, 
HCFASD = @HCFASD, 
HCFeeding = @HCFeeding, 
HCGeneral = @HCGeneral, 
HCMedicalAdvocacy = @HCMedicalAdvocacy, 
HCNutrition = @HCNutrition, 
HCOther = @HCOther, 
HCPrenatalCare = @HCPrenatalCare, 
HCProviders = @HCProviders, 
HCSafety = @HCSafety, 
HCSexEducation = @HCSexEducation, 
HCSIDS = @HCSIDS, 
HCSmoking = @HCSmoking, 
HCSpecify = @HCSpecify, 
HVCaseFK = @HVCaseFK, 
HVLogEditor = @HVLogEditor, 
HVSupervisorParticipated = @HVSupervisorParticipated, 
NonPrimaryFSWParticipated = @NonPrimaryFSWParticipated, 
NonPrimaryFSWFK = @NonPrimaryFSWFK, 
OBPParticipated = @OBPParticipated, 
OtherLocationSpecify = @OtherLocationSpecify, 
OtherParticipated = @OtherParticipated, 
PAAssessmentIssues = @PAAssessmentIssues, 
PAForms = @PAForms, 
PAGroups = @PAGroups, 
PAIFSP = @PAIFSP, 
PAOther = @PAOther, 
PARecreation = @PARecreation, 
PASpecify = @PASpecify, 
PAVideo = @PAVideo, 
ParentCompletedActivity = @ParentCompletedActivity, 
ParentObservationsDiscussed = @ParentObservationsDiscussed, 
ParticipatedSpecify = @ParticipatedSpecify, 
PC1Participated = @PC1Participated, 
PC2Participated = @PC2Participated, 
PCBasicNeeds = @PCBasicNeeds, 
PCChildInteraction = @PCChildInteraction, 
PCChildManagement = @PCChildManagement, 
PCFeelings = @PCFeelings, 
PCOther = @PCOther, 
PCShakenBaby = @PCShakenBaby, 
PCShakenBabyVideo = @PCShakenBabyVideo, 
PCSpecify = @PCSpecify, 
PCStress = @PCStress, 
ProgramFK = @ProgramFK, 
ReviewAssessmentIssues = @ReviewAssessmentIssues, 
SiblingParticipated = @SiblingParticipated, 
SSCalendar = @SSCalendar, 
SSChildCare = @SSChildCare, 
SSEducation = @SSEducation, 
SSEmployment = @SSEmployment, 
SSHousekeeping = @SSHousekeeping, 
SSJob = @SSJob, 
SSMoneyManagement = @SSMoneyManagement, 
SSOther = @SSOther, 
SSProblemSolving = @SSProblemSolving, 
SSSpecify = @SSSpecify, 
SSTransportation = @SSTransportation, 
SupervisorObservation = @SupervisorObservation, 
TCParticipated = @TCParticipated, 
TotalPercentageSpent = @TotalPercentageSpent, 
UpcomingProgramEvents = @UpcomingProgramEvents, 
VisitLengthHour = @VisitLengthHour, 
VisitLengthMinute = @VisitLengthMinute, 
VisitLocation = @VisitLocation, 
VisitStartTime = @VisitStartTime, 
VisitType = @VisitType
WHERE HVLogPK = @HVLogPK
GO
PRINT N'Adding foreign keys to [dbo].[HVLog]'
GO
ALTER TABLE [dbo].[HVLog] WITH NOCHECK  ADD CONSTRAINT [FK_HVLog_FSWFK] FOREIGN KEY ([FSWFK]) REFERENCES [dbo].[Worker] ([WorkerPK])
ALTER TABLE [dbo].[HVLog] WITH NOCHECK  ADD CONSTRAINT [FK_HVLog_HVCaseFK] FOREIGN KEY ([HVCaseFK]) REFERENCES [dbo].[HVCase] ([HVCasePK])
ALTER TABLE [dbo].[HVLog] WITH NOCHECK  ADD CONSTRAINT [FK_HVLog_ProgramFK] FOREIGN KEY ([ProgramFK]) REFERENCES [dbo].[HVProgram] ([HVProgramPK])
GO
PRINT N'Creating trigger [dbo].[fr_delete_hvlog] on [dbo].[HVLog]'
GO
Create TRIGGER [dbo].[fr_delete_hvlog]
on dbo.HVLog
After DELETE

AS

Declare @PK int

set @PK = (SELECT HVLOGPK from deleted)

BEGIN
	EXEC spDeleteFormReview_Trigger @FormFK=@PK, @FormTypeValue='VL'
END
GO
PRINT N'Creating trigger [dbo].[fr_hvlog] on [dbo].[HVLog]'
GO
CREATE TRIGGER [dbo].[fr_hvlog]
on dbo.HVLog
After insert

AS

Declare @PK int

set @PK = (SELECT HVLogPK from inserted)

BEGIN
	EXEC spAddFormReview_userTrigger @FormFK=@PK, @FormTypeValue='VL'
END
GO
PRINT N'Creating trigger [dbo].[fr_HVLog_Edit] on [dbo].[HVLog]'
GO
-- =============================================
-- Author:		Chris Papas
-- Create date: 08/18/2010
-- Description:	Updates FormReview Table with form date on Supervisor Review of Form
-- =============================================
CREATE TRIGGER [dbo].[fr_HVLog_Edit]
on dbo.HVLog
AFTER UPDATE

AS

Declare @PK int
Declare @UpdatedFormDate datetime 
Declare @FormTypeValue varchar(2)

select @PK = HVLogPK  FROM inserted
select @UpdatedFormDate = VisitStartTime FROM inserted
set @FormTypeValue = 'VL'

BEGIN
	UPDATE FormReview
	SET 
	FormDate=@UpdatedFormDate
	WHERE FormFK=@PK 
	AND FormType=@FormTypeValue

END
GO
PRINT N'Creating trigger [dbo].[TR_HVLogEditDate] on [dbo].[HVLog]'
GO
CREATE TRIGGER [dbo].[TR_HVLogEditDate] ON dbo.HVLog
For Update 
AS
Update HVLog Set HVLog.HVLogEditDate= getdate()
From [HVLog] INNER JOIN Inserted ON [HVLog].[HVLogPK]= Inserted.[HVLogPK]
GO
