SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[spIsPHQCompleteonKempe] @HVCaseFK INT AS

SELECT TOP 1 CASE WHEN p.PHQ9PK IS NOT NULL THEN 1 ELSE 0 END AS PHQ9Complete FROM Kempe k INNER JOIN PHQ9 p ON p.FormType = 'KE' AND p.FormFK = k.KempePK
WHERE k.HVCaseFk = @HVCaseFK  
GO
