SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddHVCase](@CaseProgress numeric(3, 1)=NULL,
@Confidentiality bit=NULL,
@CPFK int=NULL,
@DateOBPAdded datetime=NULL,
@EDC datetime=NULL,
@FFFK int=NULL,
@FirstChildDOB datetime=NULL,
@FirstPrenatalCareVisit datetime=NULL,
@FirstPrenatalCareVisitUnknown bit=NULL,
@HVCaseCreator varchar(max)=NULL,
@InitialZip char(10)=NULL,
@IntakeDate datetime=NULL,
@IntakeLevel char(1)=NULL,
@IntakeWorkerFK int=NULL,
@KempeDate datetime=NULL,
@OBPInformationAvailable bit=NULL,
@OBPFK int=NULL,
@OBPinHomeIntake bit=NULL,
@OBPRelation2TC char(2)=NULL,
@PC1FK int=NULL,
@PC1Relation2TC char(2)=NULL,
@PC1Relation2TCSpecify varchar(30)=NULL,
@PC2FK int=NULL,
@PC2inHomeIntake bit=NULL,
@PC2Relation2TC char(2)=NULL,
@PC2Relation2TCSpecify varchar(30)=NULL,
@PrenatalCheckupsB4 int=NULL,
@ScreenDate datetime=NULL,
@TCDOB datetime=NULL,
@TCDOD datetime=NULL,
@TCNumber int=NULL,
@KempeDate2 datetime=NULL)
AS
INSERT INTO HVCase(
CaseProgress,
Confidentiality,
CPFK,
DateOBPAdded,
EDC,
FFFK,
FirstChildDOB,
FirstPrenatalCareVisit,
FirstPrenatalCareVisitUnknown,
HVCaseCreator,
InitialZip,
IntakeDate,
IntakeLevel,
IntakeWorkerFK,
KempeDate,
OBPInformationAvailable,
OBPFK,
OBPinHomeIntake,
OBPRelation2TC,
PC1FK,
PC1Relation2TC,
PC1Relation2TCSpecify,
PC2FK,
PC2inHomeIntake,
PC2Relation2TC,
PC2Relation2TCSpecify,
PrenatalCheckupsB4,
ScreenDate,
TCDOB,
TCDOD,
TCNumber,
KempeDate2
)
VALUES(
@CaseProgress,
@Confidentiality,
@CPFK,
@DateOBPAdded,
@EDC,
@FFFK,
@FirstChildDOB,
@FirstPrenatalCareVisit,
@FirstPrenatalCareVisitUnknown,
@HVCaseCreator,
@InitialZip,
@IntakeDate,
@IntakeLevel,
@IntakeWorkerFK,
@KempeDate,
@OBPInformationAvailable,
@OBPFK,
@OBPinHomeIntake,
@OBPRelation2TC,
@PC1FK,
@PC1Relation2TC,
@PC1Relation2TCSpecify,
@PC2FK,
@PC2inHomeIntake,
@PC2Relation2TC,
@PC2Relation2TCSpecify,
@PrenatalCheckupsB4,
@ScreenDate,
@TCDOB,
@TCDOD,
@TCNumber,
@KempeDate2
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
