SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddTCID](@BirthTerm char(2)=NULL,
@BirthWtLbs int=NULL,
@BirthWtOz int=NULL,
@DeliveryType char(2)=NULL,
@Ethnicity varchar(500)=NULL,
@FedBreastMilk bit=NULL,
@FSWFK int=NULL,
@GestationalAge int=NULL,
@HVCaseFK int=NULL,
@IntensiveCare char(1)=NULL,
@MultipleBirth bit=NULL,
@NoImmunization bit=NULL,
@NumberofChildren int=NULL,
@ProgramFK int=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@SmokedPregnant char(1)=NULL,
@TCDOB datetime=NULL,
@TCDOD datetime=NULL,
@TCFirstName varchar(200)=NULL,
@TCGender char(2)=NULL,
@TCIDCreator varchar(max)=NULL,
@TCIDFormCompleteDate datetime=NULL,
@TCIDPK_old int=NULL,
@TCLastName varchar(200)=NULL,
@VaricellaZoster bit=NULL,
@NoImmunizationsReason char(2)=NULL,
@MIECHV_Race_AmericanIndian bit=NULL,
@MIECHV_Race_Asian bit=NULL,
@MIECHV_Race_Black bit=NULL,
@MIECHV_Race_Hawaiian bit=NULL,
@MIECHV_Race_White bit=NULL,
@MIECHV_Hispanic nvarchar(1)=NULL,
@Race_AmericanIndian bit=NULL,
@Race_Asian bit=NULL,
@Race_Black bit=NULL,
@Race_Hawaiian bit=NULL,
@Race_White bit=NULL,
@Race_Hispance bit=NULL)
AS
INSERT INTO TCID(
BirthTerm,
BirthWtLbs,
BirthWtOz,
DeliveryType,
Ethnicity,
FedBreastMilk,
FSWFK,
GestationalAge,
HVCaseFK,
IntensiveCare,
MultipleBirth,
NoImmunization,
NumberofChildren,
ProgramFK,
Race,
RaceSpecify,
SmokedPregnant,
TCDOB,
TCDOD,
TCFirstName,
TCGender,
TCIDCreator,
TCIDFormCompleteDate,
TCIDPK_old,
TCLastName,
VaricellaZoster,
NoImmunizationsReason,
MIECHV_Race_AmericanIndian,
MIECHV_Race_Asian,
MIECHV_Race_Black,
MIECHV_Race_Hawaiian,
MIECHV_Race_White,
MIECHV_Hispanic,
Race_AmericanIndian,
Race_Asian,
Race_Black,
Race_Hawaiian,
Race_White,
Race_Hispance
)
VALUES(
@BirthTerm,
@BirthWtLbs,
@BirthWtOz,
@DeliveryType,
@Ethnicity,
@FedBreastMilk,
@FSWFK,
@GestationalAge,
@HVCaseFK,
@IntensiveCare,
@MultipleBirth,
@NoImmunization,
@NumberofChildren,
@ProgramFK,
@Race,
@RaceSpecify,
@SmokedPregnant,
@TCDOB,
@TCDOD,
@TCFirstName,
@TCGender,
@TCIDCreator,
@TCIDFormCompleteDate,
@TCIDPK_old,
@TCLastName,
@VaricellaZoster,
@NoImmunizationsReason,
@MIECHV_Race_AmericanIndian,
@MIECHV_Race_Asian,
@MIECHV_Race_Black,
@MIECHV_Race_Hawaiian,
@MIECHV_Race_White,
@MIECHV_Hispanic,
@Race_AmericanIndian,
@Race_Asian,
@Race_Black,
@Race_Hawaiian,
@Race_White,
@Race_Hispance
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
