SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddSupervision](@ActivitiesOther bit=NULL,
@ActivitiesOtherSpecify varchar(500)=NULL,
@ActivitiesOtherStatus bit=NULL,
@AreasGrowth bit=NULL,
@AreasGrowthComments varchar(max)=NULL,
@AreasGrowthStatus bit=NULL,
@AssessmentIssues bit=NULL,
@AssessmentIssuesComments varchar(max)=NULL,
@AssessmentIssuesStatus bit=NULL,
@AssessmentRate bit=NULL,
@AssessmentRateComments varchar(max)=NULL,
@AssessmentRateStatus bit=NULL,
@AssessmentScreens bit=NULL,
@AssessmentScreensComments varchar(max)=NULL,
@AssessmentScreensStatus bit=NULL,
@Boundaries bit=NULL,
@BoundariesComments varchar(max)=NULL,
@BoundariesStatus bit=NULL,
@Caseload bit=NULL,
@CaseloadComments varchar(max)=NULL,
@CaseloadStatus bit=NULL,
@CHEERSFeedback bit=NULL,
@CHEERSFeedbackComments varchar(max)=NULL,
@CHEERSFeedbackStatus bit=NULL,
@ChallengingIssues bit=NULL,
@ChallengingIssuesComments varchar(max)=NULL,
@ChallengingIssuesStatus bit=NULL,
@Coaching bit=NULL,
@CoachingComments varchar(max)=NULL,
@CoachingStatus bit=NULL,
@CommunityResources bit=NULL,
@CommunityResourcesComments varchar(max)=NULL,
@CommunityResourcesStatus bit=NULL,
@Concerns bit=NULL,
@ConcernsComments varchar(max)=NULL,
@ConcernsStatus bit=NULL,
@CPS bit=NULL,
@CPSComments varchar(max)=NULL,
@CPSStatus bit=NULL,
@CulturalSensitivity bit=NULL,
@CulturalSensitivityComments varchar(max)=NULL,
@CulturalSensitivityStatus bit=NULL,
@Curriculum bit=NULL,
@CurriculumComments varchar(max)=NULL,
@CurriculumStatus bit=NULL,
@FamilyGrievance bit=NULL,
@FamilyGrievanceComments varchar(max)=NULL,
@FamilyGrievanceStatus bit=NULL,
@FamilyProgress bit=NULL,
@FamilyProgressComments varchar(max)=NULL,
@FamilyProgressStatus bit=NULL,
@FGPProgress bit=NULL,
@FGPProgressComments varchar(max)=NULL,
@FGPProgressStatus bit=NULL,
@FormComplete bit=NULL,
@HomeVisitLogActivities bit=NULL,
@HomeVisitLogActivitiesComments varchar(max)=NULL,
@HomeVisitLogActivitiesStatus bit=NULL,
@HomeVisitRate bit=NULL,
@HomeVisitRateComments varchar(max)=NULL,
@HomeVisitRateStatus bit=NULL,
@HVCulturalSensitivity bit=NULL,
@HVCulturalSensitivityComments varchar(max)=NULL,
@HVCulturalSensitivityStatus bit=NULL,
@HVHomeVisitRate bit=NULL,
@HVHomeVisitRateComments varchar(max)=NULL,
@HVHomeVisitRateStatus bit=NULL,
@HVReferralSources bit=NULL,
@HVReferralSourcesComments varchar(max)=NULL,
@HVReferralSourcesStatus bit=NULL,
@IFSP bit=NULL,
@IFSPComments varchar(max)=NULL,
@IFSPStatus bit=NULL,
@ImpactOfWork bit=NULL,
@ImpactOfWorkComments varchar(max)=NULL,
@ImpactOfWorkStatus bit=NULL,
@ImplementTraining bit=NULL,
@ImplementTrainingComments varchar(max)=NULL,
@ImplementTrainingStatus bit=NULL,
@InterRaterReliability bit=NULL,
@InterRaterReliabilityComments varchar(max)=NULL,
@InterRaterReliabilityStatus bit=NULL,
@LevelChange bit=NULL,
@LevelChangeComments varchar(max)=NULL,
@LevelChangeStatus bit=NULL,
@Medical bit=NULL,
@MedicalComments varchar(max)=NULL,
@MedicalStatus bit=NULL,
@Outreach bit=NULL,
@OutreachComments varchar(max)=NULL,
@OutreachStatus bit=NULL,
@PersonalGrowth bit=NULL,
@PersonalGrowthComments varchar(max)=NULL,
@PersonalGrowthStatus bit=NULL,
@Personnel bit=NULL,
@PersonnelComments varchar(max)=NULL,
@PersonnelStatus bit=NULL,
@PIP bit=NULL,
@PIPComments varchar(max)=NULL,
@PIPStatus bit=NULL,
@ProfessionalGrowth bit=NULL,
@ProfessionalGrowthComments varchar(max)=NULL,
@ProfessionalGrowthStatus bit=NULL,
@ProgramFK int=NULL,
@ProtectiveFactors bit=NULL,
@ProtectiveFactorsComments varchar(max)=NULL,
@ProtectiveFactorsStatus bit=NULL,
@RecordDocumentation bit=NULL,
@RecordDocumentationComments varchar(max)=NULL,
@RecordDocumentationStatus bit=NULL,
@Referrals bit=NULL,
@ReferralsComments varchar(max)=NULL,
@ReferralsStatus bit=NULL,
@Reflection bit=NULL,
@ReflectionComments varchar(max)=NULL,
@ReflectionStatus bit=NULL,
@Retention bit=NULL,
@RetentionComments varchar(max)=NULL,
@RetentionStatus bit=NULL,
@RiskFactors bit=NULL,
@RiskFactorsComments varchar(max)=NULL,
@RiskFactorsStatus bit=NULL,
@RolePlaying bit=NULL,
@RolePlayingComments varchar(max)=NULL,
@RolePlayingStatus bit=NULL,
@Safety bit=NULL,
@SafetyComments varchar(max)=NULL,
@SafetyStatus bit=NULL,
@SiteDocumentation bit=NULL,
@SiteDocumentationComments varchar(max)=NULL,
@SiteDocumentationStatus bit=NULL,
@Shadow bit=NULL,
@ShadowComments varchar(max)=NULL,
@ShadowStatus bit=NULL,
@StrengthBasedApproach bit=NULL,
@StrengthBasedApproachComments varchar(max)=NULL,
@StrengthBasedApproachStatus bit=NULL,
@Strengths bit=NULL,
@StrengthsComments varchar(max)=NULL,
@StrengthsStatus bit=NULL,
@Successes bit=NULL,
@SuccessesComments varchar(max)=NULL,
@SuccessesStatus bit=NULL,
@SupervisionCreator char(10)=NULL,
@SupervisionDate datetime=NULL,
@SupervisionEndTime datetime=NULL,
@SupervisionHours int=NULL,
@SupervisionMinutes int=NULL,
@SupervisionNotes varchar(max)=NULL,
@SupervisionStartTime char(8)=NULL,
@SupervisorFK int=NULL,
@SupervisorObservationAssessment bit=NULL,
@SupervisorObservationAssessmentComments varchar(max)=NULL,
@SupervisorObservationAssessmentStatus bit=NULL,
@SupervisorObservationHomeVisit bit=NULL,
@SupervisorObservationHomeVisitComments varchar(max)=NULL,
@SupervisorObservationHomeVisitStatus bit=NULL,
@TakePlace bit=NULL,
@TeamDevelopment bit=NULL,
@TeamDevelopmentComments varchar(max)=NULL,
@TeamDevelopmentStatus bit=NULL,
@TechniquesApproaches bit=NULL,
@TechniquesApproachesComments varchar(max)=NULL,
@TechniquesApproachesStatus bit=NULL,
@Tools bit=NULL,
@ToolsComments varchar(max)=NULL,
@ToolsStatus bit=NULL,
@TrackingData bit=NULL,
@TrackingDataComments varchar(max)=NULL,
@TrackingDataStatus bit=NULL,
@TrainingNeeds bit=NULL,
@TrainingNeedsComments varchar(max)=NULL,
@TrainingNeedsStatus bit=NULL,
@TransitionPlanning bit=NULL,
@TransitionPlanningComments varchar(max)=NULL,
@TransitionPlanningStatus bit=NULL,
@WorkerFK int=NULL,
@ParticipantEmergency bit=NULL,
@ReasonOther bit=NULL,
@ReasonOtherSpecify varchar(500)=NULL,
@ShortWeek bit=NULL,
@StaffCourt bit=NULL,
@StaffFamilyEmergency bit=NULL,
@StaffForgot bit=NULL,
@StaffIll bit=NULL,
@StaffOnLeave bit=NULL,
@StaffTraining bit=NULL,
@StaffVacation bit=NULL,
@StaffOutAllWeek bit=NULL,
@SupervisorFamilyEmergency bit=NULL,
@SupervisorForgot bit=NULL,
@SupervisorHoliday bit=NULL,
@SupervisorIll bit=NULL,
@SupervisorTraining bit=NULL,
@SupervisorVacation bit=NULL,
@Weather bit=NULL)
AS
INSERT INTO Supervision(
ActivitiesOther,
ActivitiesOtherSpecify,
ActivitiesOtherStatus,
AreasGrowth,
AreasGrowthComments,
AreasGrowthStatus,
AssessmentIssues,
AssessmentIssuesComments,
AssessmentIssuesStatus,
AssessmentRate,
AssessmentRateComments,
AssessmentRateStatus,
AssessmentScreens,
AssessmentScreensComments,
AssessmentScreensStatus,
Boundaries,
BoundariesComments,
BoundariesStatus,
Caseload,
CaseloadComments,
CaseloadStatus,
CHEERSFeedback,
CHEERSFeedbackComments,
CHEERSFeedbackStatus,
ChallengingIssues,
ChallengingIssuesComments,
ChallengingIssuesStatus,
Coaching,
CoachingComments,
CoachingStatus,
CommunityResources,
CommunityResourcesComments,
CommunityResourcesStatus,
Concerns,
ConcernsComments,
ConcernsStatus,
CPS,
CPSComments,
CPSStatus,
CulturalSensitivity,
CulturalSensitivityComments,
CulturalSensitivityStatus,
Curriculum,
CurriculumComments,
CurriculumStatus,
FamilyGrievance,
FamilyGrievanceComments,
FamilyGrievanceStatus,
FamilyProgress,
FamilyProgressComments,
FamilyProgressStatus,
FGPProgress,
FGPProgressComments,
FGPProgressStatus,
FormComplete,
HomeVisitLogActivities,
HomeVisitLogActivitiesComments,
HomeVisitLogActivitiesStatus,
HomeVisitRate,
HomeVisitRateComments,
HomeVisitRateStatus,
HVCulturalSensitivity,
HVCulturalSensitivityComments,
HVCulturalSensitivityStatus,
HVHomeVisitRate,
HVHomeVisitRateComments,
HVHomeVisitRateStatus,
HVReferralSources,
HVReferralSourcesComments,
HVReferralSourcesStatus,
IFSP,
IFSPComments,
IFSPStatus,
ImpactOfWork,
ImpactOfWorkComments,
ImpactOfWorkStatus,
ImplementTraining,
ImplementTrainingComments,
ImplementTrainingStatus,
InterRaterReliability,
InterRaterReliabilityComments,
InterRaterReliabilityStatus,
LevelChange,
LevelChangeComments,
LevelChangeStatus,
Medical,
MedicalComments,
MedicalStatus,
Outreach,
OutreachComments,
OutreachStatus,
PersonalGrowth,
PersonalGrowthComments,
PersonalGrowthStatus,
Personnel,
PersonnelComments,
PersonnelStatus,
PIP,
PIPComments,
PIPStatus,
ProfessionalGrowth,
ProfessionalGrowthComments,
ProfessionalGrowthStatus,
ProgramFK,
ProtectiveFactors,
ProtectiveFactorsComments,
ProtectiveFactorsStatus,
RecordDocumentation,
RecordDocumentationComments,
RecordDocumentationStatus,
Referrals,
ReferralsComments,
ReferralsStatus,
Reflection,
ReflectionComments,
ReflectionStatus,
Retention,
RetentionComments,
RetentionStatus,
RiskFactors,
RiskFactorsComments,
RiskFactorsStatus,
RolePlaying,
RolePlayingComments,
RolePlayingStatus,
Safety,
SafetyComments,
SafetyStatus,
SiteDocumentation,
SiteDocumentationComments,
SiteDocumentationStatus,
Shadow,
ShadowComments,
ShadowStatus,
StrengthBasedApproach,
StrengthBasedApproachComments,
StrengthBasedApproachStatus,
Strengths,
StrengthsComments,
StrengthsStatus,
Successes,
SuccessesComments,
SuccessesStatus,
SupervisionCreator,
SupervisionDate,
SupervisionEndTime,
SupervisionHours,
SupervisionMinutes,
SupervisionNotes,
SupervisionStartTime,
SupervisorFK,
SupervisorObservationAssessment,
SupervisorObservationAssessmentComments,
SupervisorObservationAssessmentStatus,
SupervisorObservationHomeVisit,
SupervisorObservationHomeVisitComments,
SupervisorObservationHomeVisitStatus,
TakePlace,
TeamDevelopment,
TeamDevelopmentComments,
TeamDevelopmentStatus,
TechniquesApproaches,
TechniquesApproachesComments,
TechniquesApproachesStatus,
Tools,
ToolsComments,
ToolsStatus,
TrackingData,
TrackingDataComments,
TrackingDataStatus,
TrainingNeeds,
TrainingNeedsComments,
TrainingNeedsStatus,
TransitionPlanning,
TransitionPlanningComments,
TransitionPlanningStatus,
WorkerFK,
ParticipantEmergency,
ReasonOther,
ReasonOtherSpecify,
ShortWeek,
StaffCourt,
StaffFamilyEmergency,
StaffForgot,
StaffIll,
StaffOnLeave,
StaffTraining,
StaffVacation,
StaffOutAllWeek,
SupervisorFamilyEmergency,
SupervisorForgot,
SupervisorHoliday,
SupervisorIll,
SupervisorTraining,
SupervisorVacation,
Weather
)
VALUES(
@ActivitiesOther,
@ActivitiesOtherSpecify,
@ActivitiesOtherStatus,
@AreasGrowth,
@AreasGrowthComments,
@AreasGrowthStatus,
@AssessmentIssues,
@AssessmentIssuesComments,
@AssessmentIssuesStatus,
@AssessmentRate,
@AssessmentRateComments,
@AssessmentRateStatus,
@AssessmentScreens,
@AssessmentScreensComments,
@AssessmentScreensStatus,
@Boundaries,
@BoundariesComments,
@BoundariesStatus,
@Caseload,
@CaseloadComments,
@CaseloadStatus,
@CHEERSFeedback,
@CHEERSFeedbackComments,
@CHEERSFeedbackStatus,
@ChallengingIssues,
@ChallengingIssuesComments,
@ChallengingIssuesStatus,
@Coaching,
@CoachingComments,
@CoachingStatus,
@CommunityResources,
@CommunityResourcesComments,
@CommunityResourcesStatus,
@Concerns,
@ConcernsComments,
@ConcernsStatus,
@CPS,
@CPSComments,
@CPSStatus,
@CulturalSensitivity,
@CulturalSensitivityComments,
@CulturalSensitivityStatus,
@Curriculum,
@CurriculumComments,
@CurriculumStatus,
@FamilyGrievance,
@FamilyGrievanceComments,
@FamilyGrievanceStatus,
@FamilyProgress,
@FamilyProgressComments,
@FamilyProgressStatus,
@FGPProgress,
@FGPProgressComments,
@FGPProgressStatus,
@FormComplete,
@HomeVisitLogActivities,
@HomeVisitLogActivitiesComments,
@HomeVisitLogActivitiesStatus,
@HomeVisitRate,
@HomeVisitRateComments,
@HomeVisitRateStatus,
@HVCulturalSensitivity,
@HVCulturalSensitivityComments,
@HVCulturalSensitivityStatus,
@HVHomeVisitRate,
@HVHomeVisitRateComments,
@HVHomeVisitRateStatus,
@HVReferralSources,
@HVReferralSourcesComments,
@HVReferralSourcesStatus,
@IFSP,
@IFSPComments,
@IFSPStatus,
@ImpactOfWork,
@ImpactOfWorkComments,
@ImpactOfWorkStatus,
@ImplementTraining,
@ImplementTrainingComments,
@ImplementTrainingStatus,
@InterRaterReliability,
@InterRaterReliabilityComments,
@InterRaterReliabilityStatus,
@LevelChange,
@LevelChangeComments,
@LevelChangeStatus,
@Medical,
@MedicalComments,
@MedicalStatus,
@Outreach,
@OutreachComments,
@OutreachStatus,
@PersonalGrowth,
@PersonalGrowthComments,
@PersonalGrowthStatus,
@Personnel,
@PersonnelComments,
@PersonnelStatus,
@PIP,
@PIPComments,
@PIPStatus,
@ProfessionalGrowth,
@ProfessionalGrowthComments,
@ProfessionalGrowthStatus,
@ProgramFK,
@ProtectiveFactors,
@ProtectiveFactorsComments,
@ProtectiveFactorsStatus,
@RecordDocumentation,
@RecordDocumentationComments,
@RecordDocumentationStatus,
@Referrals,
@ReferralsComments,
@ReferralsStatus,
@Reflection,
@ReflectionComments,
@ReflectionStatus,
@Retention,
@RetentionComments,
@RetentionStatus,
@RiskFactors,
@RiskFactorsComments,
@RiskFactorsStatus,
@RolePlaying,
@RolePlayingComments,
@RolePlayingStatus,
@Safety,
@SafetyComments,
@SafetyStatus,
@SiteDocumentation,
@SiteDocumentationComments,
@SiteDocumentationStatus,
@Shadow,
@ShadowComments,
@ShadowStatus,
@StrengthBasedApproach,
@StrengthBasedApproachComments,
@StrengthBasedApproachStatus,
@Strengths,
@StrengthsComments,
@StrengthsStatus,
@Successes,
@SuccessesComments,
@SuccessesStatus,
@SupervisionCreator,
@SupervisionDate,
@SupervisionEndTime,
@SupervisionHours,
@SupervisionMinutes,
@SupervisionNotes,
@SupervisionStartTime,
@SupervisorFK,
@SupervisorObservationAssessment,
@SupervisorObservationAssessmentComments,
@SupervisorObservationAssessmentStatus,
@SupervisorObservationHomeVisit,
@SupervisorObservationHomeVisitComments,
@SupervisorObservationHomeVisitStatus,
@TakePlace,
@TeamDevelopment,
@TeamDevelopmentComments,
@TeamDevelopmentStatus,
@TechniquesApproaches,
@TechniquesApproachesComments,
@TechniquesApproachesStatus,
@Tools,
@ToolsComments,
@ToolsStatus,
@TrackingData,
@TrackingDataComments,
@TrackingDataStatus,
@TrainingNeeds,
@TrainingNeedsComments,
@TrainingNeedsStatus,
@TransitionPlanning,
@TransitionPlanningComments,
@TransitionPlanningStatus,
@WorkerFK,
@ParticipantEmergency,
@ReasonOther,
@ReasonOtherSpecify,
@ShortWeek,
@StaffCourt,
@StaffFamilyEmergency,
@StaffForgot,
@StaffIll,
@StaffOnLeave,
@StaffTraining,
@StaffVacation,
@StaffOutAllWeek,
@SupervisorFamilyEmergency,
@SupervisorForgot,
@SupervisorHoliday,
@SupervisorIll,
@SupervisorTraining,
@SupervisorVacation,
@Weather
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
