SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[spDoesTCMedicalExitst] @TCItemDate DATETIME, @TCIDFK INT AS

SELECT TOP 1 * FROM dbo.TCMedical WHERE TCItemDate = @TCItemdate AND TCIDFK = @TCIDFK
GO
