SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddSupervisionHomeVisitCase](@ActivitiesOther bit=NULL,
@ActivitiesOtherSpecify varchar(500)=NULL,
@ActivitiesOtherStatus bit=NULL,
@CaseComments varchar(max)=NULL,
@ChallengingIssues bit=NULL,
@ChallengingIssuesComments varchar(max)=NULL,
@ChallengingIssuesStatus bit=NULL,
@CHEERSFeedback bit=NULL,
@CHEERSFeedbackComments varchar(max)=NULL,
@CHEERSFeedbackStatus bit=NULL,
@Concerns bit=NULL,
@ConcernsComments varchar(max)=NULL,
@ConcernsStatus bit=NULL,
@Curriculum bit=NULL,
@CurriculumComments varchar(max)=NULL,
@CurriculumStatus bit=NULL,
@FamilyGrievance bit=NULL,
@FamilyGrievanceComments varchar(max)=NULL,
@FamilyGrievanceStatus bit=NULL,
@FGPProgress bit=NULL,
@FGPProgressComments varchar(max)=NULL,
@FGPProgressStatus bit=NULL,
@HVCaseFK int=NULL,
@HVCulturalSensitivity bit=NULL,
@HVCulturalSensitivityComments varchar(max)=NULL,
@HVCulturalSensitivityStatus bit=NULL,
@HVHomeVisitRate bit=NULL,
@HVHomeVisitRateComments varchar(max)=NULL,
@HVHomeVisitRateStatus bit=NULL,
@HVReferralSources bit=NULL,
@HVReferralSourcesComments varchar(max)=NULL,
@HVReferralSourcesStatus bit=NULL,
@LevelChange bit=NULL,
@LevelChangeComments varchar(max)=NULL,
@LevelChangeStatus bit=NULL,
@Medical bit=NULL,
@MedicalComments varchar(max)=NULL,
@MedicalStatus bit=NULL,
@ProgramFK int=NULL,
@Successes bit=NULL,
@SuccessesComments varchar(max)=NULL,
@SuccessesStatus bit=NULL,
@SupervisionFK int=NULL,
@Tools bit=NULL,
@ToolsComments varchar(max)=NULL,
@ToolsStatus bit=NULL,
@TransitionPlanning bit=NULL,
@TransitionPlanningComments varchar(max)=NULL,
@TransitionPlanningStatus bit=NULL)
AS
INSERT INTO SupervisionHomeVisitCase(
ActivitiesOther,
ActivitiesOtherSpecify,
ActivitiesOtherStatus,
CaseComments,
ChallengingIssues,
ChallengingIssuesComments,
ChallengingIssuesStatus,
CHEERSFeedback,
CHEERSFeedbackComments,
CHEERSFeedbackStatus,
Concerns,
ConcernsComments,
ConcernsStatus,
Curriculum,
CurriculumComments,
CurriculumStatus,
FamilyGrievance,
FamilyGrievanceComments,
FamilyGrievanceStatus,
FGPProgress,
FGPProgressComments,
FGPProgressStatus,
HVCaseFK,
HVCulturalSensitivity,
HVCulturalSensitivityComments,
HVCulturalSensitivityStatus,
HVHomeVisitRate,
HVHomeVisitRateComments,
HVHomeVisitRateStatus,
HVReferralSources,
HVReferralSourcesComments,
HVReferralSourcesStatus,
LevelChange,
LevelChangeComments,
LevelChangeStatus,
Medical,
MedicalComments,
MedicalStatus,
ProgramFK,
Successes,
SuccessesComments,
SuccessesStatus,
SupervisionFK,
Tools,
ToolsComments,
ToolsStatus,
TransitionPlanning,
TransitionPlanningComments,
TransitionPlanningStatus
)
VALUES(
@ActivitiesOther,
@ActivitiesOtherSpecify,
@ActivitiesOtherStatus,
@CaseComments,
@ChallengingIssues,
@ChallengingIssuesComments,
@ChallengingIssuesStatus,
@CHEERSFeedback,
@CHEERSFeedbackComments,
@CHEERSFeedbackStatus,
@Concerns,
@ConcernsComments,
@ConcernsStatus,
@Curriculum,
@CurriculumComments,
@CurriculumStatus,
@FamilyGrievance,
@FamilyGrievanceComments,
@FamilyGrievanceStatus,
@FGPProgress,
@FGPProgressComments,
@FGPProgressStatus,
@HVCaseFK,
@HVCulturalSensitivity,
@HVCulturalSensitivityComments,
@HVCulturalSensitivityStatus,
@HVHomeVisitRate,
@HVHomeVisitRateComments,
@HVHomeVisitRateStatus,
@HVReferralSources,
@HVReferralSourcesComments,
@HVReferralSourcesStatus,
@LevelChange,
@LevelChangeComments,
@LevelChangeStatus,
@Medical,
@MedicalComments,
@MedicalStatus,
@ProgramFK,
@Successes,
@SuccessesComments,
@SuccessesStatus,
@SupervisionFK,
@Tools,
@ToolsComments,
@ToolsStatus,
@TransitionPlanning,
@TransitionPlanningComments,
@TransitionPlanningStatus
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
