SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[SPGetTCMedicalsbyDateandTCID] @date VARCHAR(max), @TCID INT AS 

SELECT * FROM dbo.TCMedical WHERE TCItemDate = @date AND TCIDFK  = @TCID
GO
