SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddWorkerProgram](@BackgroundCheckDate date=NULL,
@CommunityOutreach bit=NULL,
@DirectParticipantServices bit=NULL,
@FatherAdvocate bit=NULL,
@FatherAdvocateEndDate datetime=NULL,
@FatherAdvocateStartDate datetime=NULL,
@FAW bit=NULL,
@FAWEndDate datetime=NULL,
@FAWStartDate datetime=NULL,
@FSW bit=NULL,
@FSWEndDate datetime=NULL,
@FSWStartDate datetime=NULL,
@FundRaiser bit=NULL,
@HireDate datetime=NULL,
@LivesTargetArea bit=NULL,
@ProgramFK int=NULL,
@ProgramManager bit=NULL,
@ProgramManagerEndDate datetime=NULL,
@ProgramManagerStartDate datetime=NULL,
@SiteFK int=NULL,
@Supervisor bit=NULL,
@SupervisorEndDate datetime=NULL,
@SupervisorFK int=NULL,
@SupervisorStartDate datetime=NULL,
@TerminationDate datetime=NULL,
@TerminationReasonRetired bit=NULL,
@TerminationReasonForbetterJob bit=NULL,
@TerminationReasonMoved bit=NULL,
@TerminationReasonMoney bit=NULL,
@TerminationReasonBaby bit=NULL,
@TerminationReasonPromotion bit=NULL,
@TerminationReasonDisability bit=NULL,
@TerminationReasonNotGoodFit bit=NULL,
@TerminationReasonIncarceration bit=NULL,
@TerminationReasonInvoluntary bit=NULL,
@TerminationReasonReassigned bit=NULL,
@TerminationReasonLossFunding bit=NULL,
@TerminationReasonBackToSchool bit=NULL,
@TerminationReasonOther bit=NULL,
@TerminationReasonOtherSpecify varchar(50)=NULL,
@WorkerFK int=NULL,
@WorkerNotes varchar(500)=NULL,
@WorkerProgramCreator char(10)=NULL,
@WorkPhone char(12)=NULL)
AS
INSERT INTO WorkerProgram(
BackgroundCheckDate,
CommunityOutreach,
DirectParticipantServices,
FatherAdvocate,
FatherAdvocateEndDate,
FatherAdvocateStartDate,
FAW,
FAWEndDate,
FAWStartDate,
FSW,
FSWEndDate,
FSWStartDate,
FundRaiser,
HireDate,
LivesTargetArea,
ProgramFK,
ProgramManager,
ProgramManagerEndDate,
ProgramManagerStartDate,
SiteFK,
Supervisor,
SupervisorEndDate,
SupervisorFK,
SupervisorStartDate,
TerminationDate,
TerminationReasonRetired,
TerminationReasonForbetterJob,
TerminationReasonMoved,
TerminationReasonMoney,
TerminationReasonBaby,
TerminationReasonPromotion,
TerminationReasonDisability,
TerminationReasonNotGoodFit,
TerminationReasonIncarceration,
TerminationReasonInvoluntary,
TerminationReasonReassigned,
TerminationReasonLossFunding,
TerminationReasonBackToSchool,
TerminationReasonOther,
TerminationReasonOtherSpecify,
WorkerFK,
WorkerNotes,
WorkerProgramCreator,
WorkPhone
)
VALUES(
@BackgroundCheckDate,
@CommunityOutreach,
@DirectParticipantServices,
@FatherAdvocate,
@FatherAdvocateEndDate,
@FatherAdvocateStartDate,
@FAW,
@FAWEndDate,
@FAWStartDate,
@FSW,
@FSWEndDate,
@FSWStartDate,
@FundRaiser,
@HireDate,
@LivesTargetArea,
@ProgramFK,
@ProgramManager,
@ProgramManagerEndDate,
@ProgramManagerStartDate,
@SiteFK,
@Supervisor,
@SupervisorEndDate,
@SupervisorFK,
@SupervisorStartDate,
@TerminationDate,
@TerminationReasonRetired,
@TerminationReasonForbetterJob,
@TerminationReasonMoved,
@TerminationReasonMoney,
@TerminationReasonBaby,
@TerminationReasonPromotion,
@TerminationReasonDisability,
@TerminationReasonNotGoodFit,
@TerminationReasonIncarceration,
@TerminationReasonInvoluntary,
@TerminationReasonReassigned,
@TerminationReasonLossFunding,
@TerminationReasonBackToSchool,
@TerminationReasonOther,
@TerminationReasonOtherSpecify,
@WorkerFK,
@WorkerNotes,
@WorkerProgramCreator,
@WorkPhone
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
