SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditSupervisionHomeVisitCase](@SupervisionHomeVisitCasePK int=NULL,
@CaseComments varchar(max)=NULL,
@ChallengingIssues bit=NULL,
@ChallengingIssuesComments varchar(max)=NULL,
@ChallengingIssuesStatus bit=NULL,
@CHEERSFeedback bit=NULL,
@CHEERSFeedbackComments varchar(max)=NULL,
@CHEERSFeedbackStatus bit=NULL,
@FGPProgress bit=NULL,
@FGPProgressComments varchar(max)=NULL,
@FGPProgressStatus bit=NULL,
@FollowUpHVCase bit=NULL,
@HVCaseFK int=NULL,
@HVCPS bit=NULL,
@HVCPSComments varchar(max)=NULL,
@HVCPSStatus bit=NULL,
@HVReferrals bit=NULL,
@HVReferralsComments varchar(max)=NULL,
@HVReferralsStatus bit=NULL,
@LevelChange bit=NULL,
@LevelChangeComments varchar(max)=NULL,
@LevelChangeStatus bit=NULL,
@Medical bit=NULL,
@MedicalComments varchar(max)=NULL,
@MedicalStatus bit=NULL,
@ProgramFK int=NULL,
@ServicePlan bit=NULL,
@ServicePlanComments varchar(max)=NULL,
@ServicePlanStatus bit=NULL,
@SupervisionFK int=NULL,
@SupervisionHomeVisitCaseEditor varchar(max)=NULL,
@Tools bit=NULL,
@ToolsComments varchar(max)=NULL,
@ToolsStatus bit=NULL,
@TransitionPlanning bit=NULL,
@TransitionPlanningComments varchar(max)=NULL,
@TransitionPlanningStatus bit=NULL)
AS
UPDATE SupervisionHomeVisitCase
SET 
CaseComments = @CaseComments, 
ChallengingIssues = @ChallengingIssues, 
ChallengingIssuesComments = @ChallengingIssuesComments, 
ChallengingIssuesStatus = @ChallengingIssuesStatus, 
CHEERSFeedback = @CHEERSFeedback, 
CHEERSFeedbackComments = @CHEERSFeedbackComments, 
CHEERSFeedbackStatus = @CHEERSFeedbackStatus, 
FGPProgress = @FGPProgress, 
FGPProgressComments = @FGPProgressComments, 
FGPProgressStatus = @FGPProgressStatus, 
FollowUpHVCase = @FollowUpHVCase, 
HVCaseFK = @HVCaseFK, 
HVCPS = @HVCPS, 
HVCPSComments = @HVCPSComments, 
HVCPSStatus = @HVCPSStatus, 
HVReferrals = @HVReferrals, 
HVReferralsComments = @HVReferralsComments, 
HVReferralsStatus = @HVReferralsStatus, 
LevelChange = @LevelChange, 
LevelChangeComments = @LevelChangeComments, 
LevelChangeStatus = @LevelChangeStatus, 
Medical = @Medical, 
MedicalComments = @MedicalComments, 
MedicalStatus = @MedicalStatus, 
ProgramFK = @ProgramFK, 
ServicePlan = @ServicePlan, 
ServicePlanComments = @ServicePlanComments, 
ServicePlanStatus = @ServicePlanStatus, 
SupervisionFK = @SupervisionFK, 
SupervisionHomeVisitCaseEditor = @SupervisionHomeVisitCaseEditor, 
Tools = @Tools, 
ToolsComments = @ToolsComments, 
ToolsStatus = @ToolsStatus, 
TransitionPlanning = @TransitionPlanning, 
TransitionPlanningComments = @TransitionPlanningComments, 
TransitionPlanningStatus = @TransitionPlanningStatus
WHERE SupervisionHomeVisitCasePK = @SupervisionHomeVisitCasePK
GO
