SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditTCID](@TCIDPK int=NULL,
@BirthTerm char(2)=NULL,
@BirthWtLbs int=NULL,
@BirthWtOz int=NULL,
@DeliveryType char(2)=NULL,
@Ethnicity varchar(500)=NULL,
@FedBreastMilk bit=NULL,
@FSWFK int=NULL,
@GestationalAge int=NULL,
@HVCaseFK int=NULL,
@IntensiveCare char(1)=NULL,
@MultipleBirth bit=NULL,
@NoImmunization bit=NULL,
@NumberofChildren int=NULL,
@ProgramFK int=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@SmokedPregnant char(1)=NULL,
@TCDOB datetime=NULL,
@TCDOD datetime=NULL,
@TCFirstName varchar(200)=NULL,
@TCGender char(2)=NULL,
@TCIDEditor varchar(max)=NULL,
@TCIDFormCompleteDate datetime=NULL,
@TCIDPK_old int=NULL,
@TCLastName varchar(200)=NULL,
@VaricellaZoster bit=NULL,
@NoImmunizationsReason char(2)=NULL,
@MIECHV_Race_AmericanIndian bit=NULL,
@MIECHV_Race_Asian bit=NULL,
@MIECHV_Race_Black bit=NULL,
@MIECHV_Race_Hawaiian bit=NULL,
@MIECHV_Race_White bit=NULL,
@MIECHV_Hispanic nvarchar(1)=NULL,
@Race_AmericanIndian bit=NULL,
@Race_Asian bit=NULL,
@Race_Black bit=NULL,
@Race_Hawaiian bit=NULL,
@Race_White bit=NULL,
@Race_Hispanic bit=NULL)
AS
UPDATE TCID
SET 
BirthTerm = @BirthTerm, 
BirthWtLbs = @BirthWtLbs, 
BirthWtOz = @BirthWtOz, 
DeliveryType = @DeliveryType, 
Ethnicity = @Ethnicity, 
FedBreastMilk = @FedBreastMilk, 
FSWFK = @FSWFK, 
GestationalAge = @GestationalAge, 
HVCaseFK = @HVCaseFK, 
IntensiveCare = @IntensiveCare, 
MultipleBirth = @MultipleBirth, 
NoImmunization = @NoImmunization, 
NumberofChildren = @NumberofChildren, 
ProgramFK = @ProgramFK, 
Race = @Race, 
RaceSpecify = @RaceSpecify, 
SmokedPregnant = @SmokedPregnant, 
TCDOB = @TCDOB, 
TCDOD = @TCDOD, 
TCFirstName = @TCFirstName, 
TCGender = @TCGender, 
TCIDEditor = @TCIDEditor, 
TCIDFormCompleteDate = @TCIDFormCompleteDate, 
TCIDPK_old = @TCIDPK_old, 
TCLastName = @TCLastName, 
VaricellaZoster = @VaricellaZoster, 
NoImmunizationsReason = @NoImmunizationsReason, 
MIECHV_Race_AmericanIndian = @MIECHV_Race_AmericanIndian, 
MIECHV_Race_Asian = @MIECHV_Race_Asian, 
MIECHV_Race_Black = @MIECHV_Race_Black, 
MIECHV_Race_Hawaiian = @MIECHV_Race_Hawaiian, 
MIECHV_Race_White = @MIECHV_Race_White, 
MIECHV_Hispanic = @MIECHV_Hispanic, 
Race_AmericanIndian = @Race_AmericanIndian, 
Race_Asian = @Race_Asian, 
Race_Black = @Race_Black, 
Race_Hawaiian = @Race_Hawaiian, 
Race_White = @Race_White, 
Race_Hispanic = @Race_Hispanic
WHERE TCIDPK = @TCIDPK
GO
