SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditCheersCheckIn](@CheersCheckInPK int=NULL,
@AverageCuesScore decimal(5, 2)=NULL,
@AverageEmpathyScore decimal(5, 2)=NULL,
@AverageExpressionScore decimal(5, 2)=NULL,
@AverageHoldingScore decimal(5, 2)=NULL,
@AverageRhythmScore decimal(5, 2)=NULL,
@AverageSmilesScore decimal(5, 2)=NULL,
@CheersCheckInEditor varchar(10)=NULL,
@Cues1Score int=NULL,
@Cues2Score int=NULL,
@Empathy1Score int=NULL,
@Empathy2Score int=NULL,
@Empathy3Score int=NULL,
@Expression1Score int=NULL,
@Expression2Score int=NULL,
@Expression3Score int=NULL,
@FSWFK int=NULL,
@Holding1Score int=NULL,
@Holding2Score int=NULL,
@Holding3Score int=NULL,
@HVCaseFK int=NULL,
@ObservationDate datetime=NULL,
@ProgramFK int=NULL,
@Rhythm1Score int=NULL,
@Rhythm2Score int=NULL,
@Smiles1Score int=NULL,
@Smiles2Score int=NULL,
@Smiles3Score int=NULL,
@TotalScore decimal(5, 2)=NULL)
AS
UPDATE CheersCheckIn
SET 
AverageCuesScore = @AverageCuesScore, 
AverageEmpathyScore = @AverageEmpathyScore, 
AverageExpressionScore = @AverageExpressionScore, 
AverageHoldingScore = @AverageHoldingScore, 
AverageRhythmScore = @AverageRhythmScore, 
AverageSmilesScore = @AverageSmilesScore, 
CheersCheckInEditor = @CheersCheckInEditor, 
Cues1Score = @Cues1Score, 
Cues2Score = @Cues2Score, 
Empathy1Score = @Empathy1Score, 
Empathy2Score = @Empathy2Score, 
Empathy3Score = @Empathy3Score, 
Expression1Score = @Expression1Score, 
Expression2Score = @Expression2Score, 
Expression3Score = @Expression3Score, 
FSWFK = @FSWFK, 
Holding1Score = @Holding1Score, 
Holding2Score = @Holding2Score, 
Holding3Score = @Holding3Score, 
HVCaseFK = @HVCaseFK, 
ObservationDate = @ObservationDate, 
ProgramFK = @ProgramFK, 
Rhythm1Score = @Rhythm1Score, 
Rhythm2Score = @Rhythm2Score, 
Smiles1Score = @Smiles1Score, 
Smiles2Score = @Smiles2Score, 
Smiles3Score = @Smiles3Score, 
TotalScore = @TotalScore
WHERE CheersCheckInPK = @CheersCheckInPK
GO
