SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spGetMIECHVEligiblebyPK]

(@MIECHVEligiblePK int)
AS
SET NOCOUNT ON;

SELECT * 
FROM MIECHVEligible
WHERE MIECHVEligiblePK = @MIECHVEligiblePK
GO
