SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddNewsEntry](@EntryDate datetime=NULL)
AS
INSERT INTO NewsEntry(
EntryDate
)
VALUES(
@EntryDate
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
