SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spGetCIFollowUPbyPK]

(@CIFollowUPPK int)
AS
SET NOCOUNT ON;

SELECT * 
FROM CIFollowUP
WHERE CIFollowUPPK = @CIFollowUPPK
GO
