SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditPC1ID](@PC1IDPK int=NULL,
@NextNum int=NULL)
AS
UPDATE PC1ID
SET 
NextNum = @NextNum
WHERE PC1IDPK = @PC1IDPK
GO
