SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddSupervisionDeleted](@SupervisionPK int=NULL,
@Boundaries bit=NULL,
@BoundariesComments varchar(max)=NULL,
@BoundariesStatus bit=NULL,
@Caseload bit=NULL,
@CaseloadComments varchar(max)=NULL,
@CaseloadStatus bit=NULL,
@Coaching bit=NULL,
@CoachingComments varchar(max)=NULL,
@CoachingStatus bit=NULL,
@CPS bit=NULL,
@CPSComments varchar(max)=NULL,
@CPSStatus bit=NULL,
@Curriculum bit=NULL,
@CurriculumComments varchar(max)=NULL,
@CurriculumStatus bit=NULL,
@FamilyReview bit=NULL,
@FamilyReviewComments varchar(max)=NULL,
@FamilyReviewStatus bit=NULL,
@FormComplete bit=NULL,
@ImpactOfWork bit=NULL,
@ImpactOfWorkComments varchar(max)=NULL,
@ImpactOfWorkStatus bit=NULL,
@ImplementTraining bit=NULL,
@ImplementTrainingComments varchar(max)=NULL,
@ImplementTrainingStatus bit=NULL,
@Outreach bit=NULL,
@OutreachComments varchar(max)=NULL,
@OutreachStatus bit=NULL,
@Personnel bit=NULL,
@PersonnelComments varchar(max)=NULL,
@PersonnelStatus bit=NULL,
@PIP bit=NULL,
@PIPComments varchar(max)=NULL,
@PIPStatus bit=NULL,
@ProfessionalGrowth bit=NULL,
@ProfessionalGrowthComments varchar(max)=NULL,
@ProfessionalGrowthStatus bit=NULL,
@ProgramFK int=NULL,
@RecordDocumentation bit=NULL,
@RecordDocumentationComments varchar(max)=NULL,
@RecordDocumentationStatus bit=NULL,
@Retention bit=NULL,
@RetentionComments varchar(max)=NULL,
@RetentionStatus bit=NULL,
@RolePlaying bit=NULL,
@RolePlayingComments varchar(max)=NULL,
@RolePlayingStatus bit=NULL,
@Safety bit=NULL,
@SafetyComments varchar(max)=NULL,
@SafetyStatus bit=NULL,
@SiteDocumentation bit=NULL,
@SiteDocumentationComments varchar(max)=NULL,
@SiteDocumentationStatus bit=NULL,
@Strengths bit=NULL,
@StrengthsComments varchar(max)=NULL,
@StrengthsStatus bit=NULL,
@SupervisionCreator char(10)=NULL,
@SupervisionDate datetime=NULL,
@SupervisionDeleteDate datetime=NULL,
@SupervisionDeleter char(10)=NULL,
@SupervisionEndTime datetime=NULL,
@SupervisionHours int=NULL,
@SupervisionMinutes int=NULL,
@SupervisionNotes varchar(max)=NULL,
@SupervisionSessionType char(1)=NULL,
@SupervisionStartTime char(8)=NULL,
@SupervisorFK int=NULL,
@SupervisorObservationAssessment bit=NULL,
@SupervisorObservationAssessmentComments varchar(max)=NULL,
@SupervisorObservationAssessmentStatus bit=NULL,
@SupervisorObservationHomeVisit bit=NULL,
@SupervisorObservationHomeVisitComments varchar(max)=NULL,
@SupervisorObservationHomeVisitStatus bit=NULL,
@SupervisorObservationSupervision bit=NULL,
@SupervisorObservationSupervisionComments varchar(max)=NULL,
@SupervisorObservationSupervisionStatus bit=NULL,
@SupportHFAModel bit=NULL,
@SupportHFAModelComments varchar(max)=NULL,
@SupportHFAModelStatus bit=NULL,
@TeamDevelopment bit=NULL,
@TeamDevelopmentComments varchar(max)=NULL,
@TeamDevelopmentStatus bit=NULL,
@WorkerFK int=NULL,
@ParticipantEmergency bit=NULL,
@ReasonOther bit=NULL,
@ReasonOtherSpecify varchar(500)=NULL,
@ShortWeek bit=NULL,
@StaffCourt bit=NULL,
@StaffFamilyEmergency bit=NULL,
@StaffForgot bit=NULL,
@StaffIll bit=NULL,
@StaffOnLeave bit=NULL,
@StaffTraining bit=NULL,
@StaffVacation bit=NULL,
@StaffOutAllWeek bit=NULL,
@SupervisorFamilyEmergency bit=NULL,
@SupervisorForgot bit=NULL,
@SupervisorHoliday bit=NULL,
@SupervisorIll bit=NULL,
@SupervisorTraining bit=NULL,
@SupervisorVacation bit=NULL,
@Weather bit=NULL)
AS
INSERT INTO SupervisionDeleted(
SupervisionPK,
Boundaries,
BoundariesComments,
BoundariesStatus,
Caseload,
CaseloadComments,
CaseloadStatus,
Coaching,
CoachingComments,
CoachingStatus,
CPS,
CPSComments,
CPSStatus,
Curriculum,
CurriculumComments,
CurriculumStatus,
FamilyReview,
FamilyReviewComments,
FamilyReviewStatus,
FormComplete,
ImpactOfWork,
ImpactOfWorkComments,
ImpactOfWorkStatus,
ImplementTraining,
ImplementTrainingComments,
ImplementTrainingStatus,
Outreach,
OutreachComments,
OutreachStatus,
Personnel,
PersonnelComments,
PersonnelStatus,
PIP,
PIPComments,
PIPStatus,
ProfessionalGrowth,
ProfessionalGrowthComments,
ProfessionalGrowthStatus,
ProgramFK,
RecordDocumentation,
RecordDocumentationComments,
RecordDocumentationStatus,
Retention,
RetentionComments,
RetentionStatus,
RolePlaying,
RolePlayingComments,
RolePlayingStatus,
Safety,
SafetyComments,
SafetyStatus,
SiteDocumentation,
SiteDocumentationComments,
SiteDocumentationStatus,
Strengths,
StrengthsComments,
StrengthsStatus,
SupervisionCreator,
SupervisionDate,
SupervisionDeleteDate,
SupervisionDeleter,
SupervisionEndTime,
SupervisionHours,
SupervisionMinutes,
SupervisionNotes,
SupervisionSessionType,
SupervisionStartTime,
SupervisorFK,
SupervisorObservationAssessment,
SupervisorObservationAssessmentComments,
SupervisorObservationAssessmentStatus,
SupervisorObservationHomeVisit,
SupervisorObservationHomeVisitComments,
SupervisorObservationHomeVisitStatus,
SupervisorObservationSupervision,
SupervisorObservationSupervisionComments,
SupervisorObservationSupervisionStatus,
SupportHFAModel,
SupportHFAModelComments,
SupportHFAModelStatus,
TeamDevelopment,
TeamDevelopmentComments,
TeamDevelopmentStatus,
WorkerFK,
ParticipantEmergency,
ReasonOther,
ReasonOtherSpecify,
ShortWeek,
StaffCourt,
StaffFamilyEmergency,
StaffForgot,
StaffIll,
StaffOnLeave,
StaffTraining,
StaffVacation,
StaffOutAllWeek,
SupervisorFamilyEmergency,
SupervisorForgot,
SupervisorHoliday,
SupervisorIll,
SupervisorTraining,
SupervisorVacation,
Weather
)
VALUES(
@SupervisionPK,
@Boundaries,
@BoundariesComments,
@BoundariesStatus,
@Caseload,
@CaseloadComments,
@CaseloadStatus,
@Coaching,
@CoachingComments,
@CoachingStatus,
@CPS,
@CPSComments,
@CPSStatus,
@Curriculum,
@CurriculumComments,
@CurriculumStatus,
@FamilyReview,
@FamilyReviewComments,
@FamilyReviewStatus,
@FormComplete,
@ImpactOfWork,
@ImpactOfWorkComments,
@ImpactOfWorkStatus,
@ImplementTraining,
@ImplementTrainingComments,
@ImplementTrainingStatus,
@Outreach,
@OutreachComments,
@OutreachStatus,
@Personnel,
@PersonnelComments,
@PersonnelStatus,
@PIP,
@PIPComments,
@PIPStatus,
@ProfessionalGrowth,
@ProfessionalGrowthComments,
@ProfessionalGrowthStatus,
@ProgramFK,
@RecordDocumentation,
@RecordDocumentationComments,
@RecordDocumentationStatus,
@Retention,
@RetentionComments,
@RetentionStatus,
@RolePlaying,
@RolePlayingComments,
@RolePlayingStatus,
@Safety,
@SafetyComments,
@SafetyStatus,
@SiteDocumentation,
@SiteDocumentationComments,
@SiteDocumentationStatus,
@Strengths,
@StrengthsComments,
@StrengthsStatus,
@SupervisionCreator,
@SupervisionDate,
@SupervisionDeleteDate,
@SupervisionDeleter,
@SupervisionEndTime,
@SupervisionHours,
@SupervisionMinutes,
@SupervisionNotes,
@SupervisionSessionType,
@SupervisionStartTime,
@SupervisorFK,
@SupervisorObservationAssessment,
@SupervisorObservationAssessmentComments,
@SupervisorObservationAssessmentStatus,
@SupervisorObservationHomeVisit,
@SupervisorObservationHomeVisitComments,
@SupervisorObservationHomeVisitStatus,
@SupervisorObservationSupervision,
@SupervisorObservationSupervisionComments,
@SupervisorObservationSupervisionStatus,
@SupportHFAModel,
@SupportHFAModelComments,
@SupportHFAModelStatus,
@TeamDevelopment,
@TeamDevelopmentComments,
@TeamDevelopmentStatus,
@WorkerFK,
@ParticipantEmergency,
@ReasonOther,
@ReasonOtherSpecify,
@ShortWeek,
@StaffCourt,
@StaffFamilyEmergency,
@StaffForgot,
@StaffIll,
@StaffOnLeave,
@StaffTraining,
@StaffVacation,
@StaffOutAllWeek,
@SupervisorFamilyEmergency,
@SupervisorForgot,
@SupervisorHoliday,
@SupervisorIll,
@SupervisorTraining,
@SupervisorVacation,
@Weather
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
