SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditSupervisionParentSurveyCase](@SupervisionParentSurveyCasePK int=NULL,
@AssessmentIssues bit=NULL,
@AssessmentIssuesComments varchar(max)=NULL,
@AssessmentIssuesStatus bit=NULL,
@AssessmentScreens bit=NULL,
@AssessmentScreensComments varchar(max)=NULL,
@AssessmentScreensStatus bit=NULL,
@CaseComments varchar(max)=NULL,
@CommunityResources bit=NULL,
@CommunityResourcesComments varchar(max)=NULL,
@CommunityResourcesStatus bit=NULL,
@CulturalSensitivity bit=NULL,
@CulturalSensitivityComments varchar(max)=NULL,
@CulturalSensitivityStatus bit=NULL,
@HVCaseFK int=NULL,
@InterRaterReliability bit=NULL,
@InterRaterReliabilityComments varchar(max)=NULL,
@InterRaterReliabilityStatus bit=NULL,
@ProgramFK int=NULL,
@ProtectiveFactors bit=NULL,
@ProtectiveFactorsComments varchar(max)=NULL,
@ProtectiveFactorsStatus bit=NULL,
@Referrals bit=NULL,
@ReferralsComments varchar(max)=NULL,
@ReferralsStatus bit=NULL,
@Reflection bit=NULL,
@ReflectionComments varchar(max)=NULL,
@ReflectionStatus bit=NULL,
@RiskFactors bit=NULL,
@RiskFactorsComments varchar(max)=NULL,
@RiskFactorsStatus bit=NULL,
@SupervisionFK int=NULL,
@TrackingData bit=NULL,
@TrackingDataComments varchar(max)=NULL,
@TrackingDataStatus bit=NULL)
AS
UPDATE SupervisionParentSurveyCase
SET 
AssessmentIssues = @AssessmentIssues, 
AssessmentIssuesComments = @AssessmentIssuesComments, 
AssessmentIssuesStatus = @AssessmentIssuesStatus, 
AssessmentScreens = @AssessmentScreens, 
AssessmentScreensComments = @AssessmentScreensComments, 
AssessmentScreensStatus = @AssessmentScreensStatus, 
CaseComments = @CaseComments, 
CommunityResources = @CommunityResources, 
CommunityResourcesComments = @CommunityResourcesComments, 
CommunityResourcesStatus = @CommunityResourcesStatus, 
CulturalSensitivity = @CulturalSensitivity, 
CulturalSensitivityComments = @CulturalSensitivityComments, 
CulturalSensitivityStatus = @CulturalSensitivityStatus, 
HVCaseFK = @HVCaseFK, 
InterRaterReliability = @InterRaterReliability, 
InterRaterReliabilityComments = @InterRaterReliabilityComments, 
InterRaterReliabilityStatus = @InterRaterReliabilityStatus, 
ProgramFK = @ProgramFK, 
ProtectiveFactors = @ProtectiveFactors, 
ProtectiveFactorsComments = @ProtectiveFactorsComments, 
ProtectiveFactorsStatus = @ProtectiveFactorsStatus, 
Referrals = @Referrals, 
ReferralsComments = @ReferralsComments, 
ReferralsStatus = @ReferralsStatus, 
Reflection = @Reflection, 
ReflectionComments = @ReflectionComments, 
ReflectionStatus = @ReflectionStatus, 
RiskFactors = @RiskFactors, 
RiskFactorsComments = @RiskFactorsComments, 
RiskFactorsStatus = @RiskFactorsStatus, 
SupervisionFK = @SupervisionFK, 
TrackingData = @TrackingData, 
TrackingDataComments = @TrackingDataComments, 
TrackingDataStatus = @TrackingDataStatus
WHERE SupervisionParentSurveyCasePK = @SupervisionParentSurveyCasePK
GO
