SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditWorker](@WorkerPK int=NULL,
@Apt char(10)=NULL,
@ASQTrainingDate datetime=NULL,
@CellPhone char(12)=NULL,
@Children bit=NULL,
@City char(20)=NULL,
@EducationLevel char(2)=NULL,
@FAWCoreDate datetime=NULL,
@FAWInitialStart datetime=NULL,
@FirstName char(20)=NULL,
@FSWCoreDate datetime=NULL,
@FSWInitialStart datetime=NULL,
@Gender char(2)=NULL,
@HomePhone char(12)=NULL,
@LanguageSpecify varchar(100)=NULL,
@LastName char(30)=NULL,
@OtherLanguage bit=NULL,
@PreviousName char(51)=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@Street char(30)=NULL,
@SupervisorCoreDate datetime=NULL,
@SupervisorFirstEvent datetime=NULL,
@SupervisorInitialStart datetime=NULL,
@WorkerDOB datetime=NULL,
@WorkerEditor char(10)=NULL,
@WorkerPK_old int=NULL,
@YoungestChild char(2)=NULL,
@Zip char(10)=NULL)
AS
UPDATE Worker
SET 
Apt = @Apt, 
ASQTrainingDate = @ASQTrainingDate, 
CellPhone = @CellPhone, 
Children = @Children, 
City = @City, 
EducationLevel = @EducationLevel, 
FAWCoreDate = @FAWCoreDate, 
FAWInitialStart = @FAWInitialStart, 
FirstName = @FirstName, 
FSWCoreDate = @FSWCoreDate, 
FSWInitialStart = @FSWInitialStart, 
Gender = @Gender, 
HomePhone = @HomePhone, 
LanguageSpecify = @LanguageSpecify, 
LastName = @LastName, 
OtherLanguage = @OtherLanguage, 
PreviousName = @PreviousName, 
Race = @Race, 
RaceSpecify = @RaceSpecify, 
Street = @Street, 
SupervisorCoreDate = @SupervisorCoreDate, 
SupervisorFirstEvent = @SupervisorFirstEvent, 
SupervisorInitialStart = @SupervisorInitialStart, 
WorkerDOB = @WorkerDOB, 
WorkerEditor = @WorkerEditor, 
WorkerPK_old = @WorkerPK_old, 
YoungestChild = @YoungestChild, 
Zip = @Zip
WHERE WorkerPK = @WorkerPK
GO
