SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddWorkerProgram](@AgencyComponent varchar(100)=NULL,
@CommunityOutreach bit=NULL,
@DirectParticipantServices bit=NULL,
@FatherAdvocate bit=NULL,
@FAW bit=NULL,
@FAWEndDate datetime=NULL,
@FAWStartDate datetime=NULL,
@FSW bit=NULL,
@FSWEndDate datetime=NULL,
@FSWStartDate datetime=NULL,
@FundRaiser bit=NULL,
@HireDate datetime=NULL,
@LivesTargetArea bit=NULL,
@ProgramFK int=NULL,
@ProgramManager bit=NULL,
@ProgramManagerEndDate datetime=NULL,
@ProgramManagerStartDate datetime=NULL,
@Supervisor bit=NULL,
@SupervisorEndDate datetime=NULL,
@SupervisorFK int=NULL,
@SupervisorStartDate datetime=NULL,
@TerminationDate datetime=NULL,
@WorkerFK int=NULL,
@WorkerNotes varchar(500)=NULL,
@WorkerProgramCreator char(10)=NULL,
@WorkPhone char(12)=NULL,
@YearEarlyChildExperience int=NULL,
@YearHVExperience int=NULL)
AS
INSERT INTO WorkerProgram(
AgencyComponent,
CommunityOutreach,
DirectParticipantServices,
FatherAdvocate,
FAW,
FAWEndDate,
FAWStartDate,
FSW,
FSWEndDate,
FSWStartDate,
FundRaiser,
HireDate,
LivesTargetArea,
ProgramFK,
ProgramManager,
ProgramManagerEndDate,
ProgramManagerStartDate,
Supervisor,
SupervisorEndDate,
SupervisorFK,
SupervisorStartDate,
TerminationDate,
WorkerFK,
WorkerNotes,
WorkerProgramCreator,
WorkPhone,
YearEarlyChildExperience,
YearHVExperience
)
VALUES(
@AgencyComponent,
@CommunityOutreach,
@DirectParticipantServices,
@FatherAdvocate,
@FAW,
@FAWEndDate,
@FAWStartDate,
@FSW,
@FSWEndDate,
@FSWStartDate,
@FundRaiser,
@HireDate,
@LivesTargetArea,
@ProgramFK,
@ProgramManager,
@ProgramManagerEndDate,
@ProgramManagerStartDate,
@Supervisor,
@SupervisorEndDate,
@SupervisorFK,
@SupervisorStartDate,
@TerminationDate,
@WorkerFK,
@WorkerNotes,
@WorkerProgramCreator,
@WorkPhone,
@YearEarlyChildExperience,
@YearHVExperience
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
