
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddSupervision](@ActivitiesOther bit=NULL,
@ActivitiesOtherSpecify varchar(500)=NULL,
@AreasGrowth bit=NULL,
@AssessmentIssues bit=NULL,
@AssessmentRate bit=NULL,
@Boundaries bit=NULL,
@Caseload bit=NULL,
@Coaching bit=NULL,
@CommunityResources bit=NULL,
@CulturalSenitivity bit=NULL,
@Curriculum bit=NULL,
@FamilyProgress bit=NULL,
@HomeVisitLogActivities bit=NULL,
@HomeVisitRate bit=NULL,
@IFSP bit=NULL,
@ImplementTraining bit=NULL,
@LevelChange bit=NULL,
@Outreach bit=NULL,
@ParticipantEmergency bit=NULL,
@PersonalGrowth bit=NULL,
@ProfessionalGrowth bit=NULL,
@ReasonOther bit=NULL,
@ReasonOtherSpecify bit=NULL,
@RecordDocumentation bit=NULL,
@Referrals bit=NULL,
@Retention bit=NULL,
@RolePlaying bit=NULL,
@Safety bit=NULL,
@ShortWeek bit=NULL,
@StaffCourt bit=NULL,
@StaffFamilyEmergency bit=NULL,
@StaffForgot bit=NULL,
@StaffIll bit=NULL,
@StaffTraining bit=NULL,
@StaffVacation bit=NULL,
@StrengthBasedApproach bit=NULL,
@Strengths bit=NULL,
@SupervisionCreator char(10)=NULL,
@SupervisionDate datetime=NULL,
@SupervisionEndTime datetime=NULL,
@SupervisionHours int=NULL,
@SupervisionMinutes int=NULL,
@SupervisionNotes varchar(max)=NULL,
@SupervisionStartTime char(8)=NULL,
@SupervisorFamilyEmergency bit=NULL,
@SupervisorFK int=NULL,
@SupervisorForgot bit=NULL,
@SupervisorHoliday bit=NULL,
@SupervisorIll bit=NULL,
@SupervisorObservationAssessment bit=NULL,
@SupervisorObservationHomeVisit bit=NULL,
@SupervisorTraining bit=NULL,
@SupervisorVacation bit=NULL,
@TakePlace bit=NULL,
@TechniquesApproaches bit=NULL,
@Tools bit=NULL,
@TrainingNeeds bit=NULL,
@Weather bit=NULL,
@WorkerFK int=NULL)
AS
INSERT INTO Supervision(
ActivitiesOther,
ActivitiesOtherSpecify,
AreasGrowth,
AssessmentIssues,
AssessmentRate,
Boundaries,
Caseload,
Coaching,
CommunityResources,
CulturalSenitivity,
Curriculum,
FamilyProgress,
HomeVisitLogActivities,
HomeVisitRate,
IFSP,
ImplementTraining,
LevelChange,
Outreach,
ParticipantEmergency,
PersonalGrowth,
ProfessionalGrowth,
ReasonOther,
ReasonOtherSpecify,
RecordDocumentation,
Referrals,
Retention,
RolePlaying,
Safety,
ShortWeek,
StaffCourt,
StaffFamilyEmergency,
StaffForgot,
StaffIll,
StaffTraining,
StaffVacation,
StrengthBasedApproach,
Strengths,
SupervisionCreator,
SupervisionDate,
SupervisionEndTime,
SupervisionHours,
SupervisionMinutes,
SupervisionNotes,
SupervisionStartTime,
SupervisorFamilyEmergency,
SupervisorFK,
SupervisorForgot,
SupervisorHoliday,
SupervisorIll,
SupervisorObservationAssessment,
SupervisorObservationHomeVisit,
SupervisorTraining,
SupervisorVacation,
TakePlace,
TechniquesApproaches,
Tools,
TrainingNeeds,
Weather,
WorkerFK
)
VALUES(
@ActivitiesOther,
@ActivitiesOtherSpecify,
@AreasGrowth,
@AssessmentIssues,
@AssessmentRate,
@Boundaries,
@Caseload,
@Coaching,
@CommunityResources,
@CulturalSenitivity,
@Curriculum,
@FamilyProgress,
@HomeVisitLogActivities,
@HomeVisitRate,
@IFSP,
@ImplementTraining,
@LevelChange,
@Outreach,
@ParticipantEmergency,
@PersonalGrowth,
@ProfessionalGrowth,
@ReasonOther,
@ReasonOtherSpecify,
@RecordDocumentation,
@Referrals,
@Retention,
@RolePlaying,
@Safety,
@ShortWeek,
@StaffCourt,
@StaffFamilyEmergency,
@StaffForgot,
@StaffIll,
@StaffTraining,
@StaffVacation,
@StrengthBasedApproach,
@Strengths,
@SupervisionCreator,
@SupervisionDate,
@SupervisionEndTime,
@SupervisionHours,
@SupervisionMinutes,
@SupervisionNotes,
@SupervisionStartTime,
@SupervisorFamilyEmergency,
@SupervisorFK,
@SupervisorForgot,
@SupervisorHoliday,
@SupervisorIll,
@SupervisorObservationAssessment,
@SupervisorObservationHomeVisit,
@SupervisorTraining,
@SupervisorVacation,
@TakePlace,
@TechniquesApproaches,
@Tools,
@TrainingNeeds,
@Weather,
@WorkerFK
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
