
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddWorker](@Apt char(10)=NULL,
@ASQTrainingDate datetime=NULL,
@CellPhone char(12)=NULL,
@Children bit=NULL,
@City char(20)=NULL,
@EducationLevel char(2)=NULL,
@FAWCoreDate datetime=NULL,
@FAWInitialStart datetime=NULL,
@FirstName char(20)=NULL,
@FSWCoreDate datetime=NULL,
@FSWInitialStart datetime=NULL,
@Gender char(2)=NULL,
@HomePhone char(12)=NULL,
@LanguageSpecify varchar(100)=NULL,
@LastName char(30)=NULL,
@OtherLanguage bit=NULL,
@PreviousName char(51)=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@Street char(30)=NULL,
@SupervisorCoreDate datetime=NULL,
@SupervisorFirstEvent datetime=NULL,
@SupervisorInitialStart datetime=NULL,
@WorkerCreator char(10)=NULL,
@WorkerDOB datetime=NULL,
@WorkerPK_old int=NULL,
@YoungestChild char(2)=NULL,
@Zip char(10)=NULL,
@LoginCreated bit=NULL)
AS
INSERT INTO Worker(
Apt,
ASQTrainingDate,
CellPhone,
Children,
City,
EducationLevel,
FAWCoreDate,
FAWInitialStart,
FirstName,
FSWCoreDate,
FSWInitialStart,
Gender,
HomePhone,
LanguageSpecify,
LastName,
OtherLanguage,
PreviousName,
Race,
RaceSpecify,
Street,
SupervisorCoreDate,
SupervisorFirstEvent,
SupervisorInitialStart,
WorkerCreator,
WorkerDOB,
WorkerPK_old,
YoungestChild,
Zip,
LoginCreated
)
VALUES(
@Apt,
@ASQTrainingDate,
@CellPhone,
@Children,
@City,
@EducationLevel,
@FAWCoreDate,
@FAWInitialStart,
@FirstName,
@FSWCoreDate,
@FSWInitialStart,
@Gender,
@HomePhone,
@LanguageSpecify,
@LastName,
@OtherLanguage,
@PreviousName,
@Race,
@RaceSpecify,
@Street,
@SupervisorCoreDate,
@SupervisorFirstEvent,
@SupervisorInitialStart,
@WorkerCreator,
@WorkerDOB,
@WorkerPK_old,
@YoungestChild,
@Zip,
@LoginCreated
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
