
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddTCID](@BirthTerm char(2)=NULL,
@BirthWtLbs int=NULL,
@BirthWtOz int=NULL,
@DeliveryType char(2)=NULL,
@Ethnicity varchar(500)=NULL,
@FedBreastMilk bit=NULL,
@FSWFK int=NULL,
@GestationalAge int=NULL,
@HVCaseFK int=NULL,
@IntensiveCare char(1)=NULL,
@MultipleBirth bit=NULL,
@NoImmunization bit=NULL,
@NumberofChildren int=NULL,
@ProgramFK int=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@SmokedPregnant char(1)=NULL,
@TCDOB datetime=NULL,
@TCDOD datetime=NULL,
@TCFirstName varchar(200)=NULL,
@TCGender char(2)=NULL,
@TCIDCreator char(10)=NULL,
@TCIDFormCompleteDate datetime=NULL,
@TCIDPK_old int=NULL,
@TCLastName varchar(200)=NULL,
@VaricellaZoster bit=NULL,
@NoImmunizationsReason char(2)=NULL)
AS
INSERT INTO TCID(
BirthTerm,
BirthWtLbs,
BirthWtOz,
DeliveryType,
Ethnicity,
FedBreastMilk,
FSWFK,
GestationalAge,
HVCaseFK,
IntensiveCare,
MultipleBirth,
NoImmunization,
NumberofChildren,
ProgramFK,
Race,
RaceSpecify,
SmokedPregnant,
TCDOB,
TCDOD,
TCFirstName,
TCGender,
TCIDCreator,
TCIDFormCompleteDate,
TCIDPK_old,
TCLastName,
VaricellaZoster,
NoImmunizationsReason
)
VALUES(
@BirthTerm,
@BirthWtLbs,
@BirthWtOz,
@DeliveryType,
@Ethnicity,
@FedBreastMilk,
@FSWFK,
@GestationalAge,
@HVCaseFK,
@IntensiveCare,
@MultipleBirth,
@NoImmunization,
@NumberofChildren,
@ProgramFK,
@Race,
@RaceSpecify,
@SmokedPregnant,
@TCDOB,
@TCDOD,
@TCFirstName,
@TCGender,
@TCIDCreator,
@TCIDFormCompleteDate,
@TCIDPK_old,
@TCLastName,
@VaricellaZoster,
@NoImmunizationsReason
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
