
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddHVLog](@CAChildSupport bit=NULL,
@CAAdvocacy bit=NULL,
@CAGoods bit=NULL,
@CAHousing bit=NULL,
@CALaborSupport bit=NULL,
@CALegal bit=NULL,
@CAOther bit=NULL,
@CAParentRights bit=NULL,
@CASpecify varchar(500)=NULL,
@CATranslation bit=NULL,
@CATransportation bit=NULL,
@CAVisitation bit=NULL,
@CDChildDevelopment bit=NULL,
@CDOther bit=NULL,
@CDSpecify varchar(500)=NULL,
@CDToys bit=NULL,
@CIProblems bit=NULL,
@CIOther bit=NULL,
@CIOtherSpecify varchar(500)=NULL,
@Curriculum247Dads bit=NULL,
@CurriculumBoyz2Dads bit=NULL,
@CurriculumGrowingGreatKids bit=NULL,
@CurriculumHelpingBabiesLearn bit=NULL,
@CurriculumInsideOutDads bit=NULL,
@CurriculumMomGateway bit=NULL,
@CurriculumOther bit=NULL,
@CurriculumOtherSpecify bit=NULL,
@CurriculumParentsForLearning bit=NULL,
@CurriculumPartnersHealthyBaby bit=NULL,
@CurriculumPAT bit=NULL,
@CurriculumPATFocusFathers bit=NULL,
@CurriculumSanAngelo bit=NULL,
@FatherAdvocateParticipated bit=NULL,
@FatherFigureParticipated bit=NULL,
@FSWFK int=NULL,
@GrandParentParticipated bit=NULL,
@HCBreastFeeding bit=NULL,
@HCChild bit=NULL,
@HCDental bit=NULL,
@HCFamilyPlanning bit=NULL,
@HCFASD bit=NULL,
@HCFeeding bit=NULL,
@HCGeneral bit=NULL,
@HCMedicalAdvocacy bit=NULL,
@HCNutrition bit=NULL,
@HCOther bit=NULL,
@HCPrenatalCare bit=NULL,
@HCProviders bit=NULL,
@HCSafety bit=NULL,
@HCSexEducation bit=NULL,
@HCSIDS bit=NULL,
@HCSmoking bit=NULL,
@HCSpecify varchar(500)=NULL,
@HVCaseFK int=NULL,
@HVLogCreator char(10)=NULL,
@HVSupervisorParticipated bit=NULL,
@NonPrimaryFSWParticipated nchar(10)=NULL,
@OBPParticipated bit=NULL,
@OtherLocationSpecify varchar(500)=NULL,
@OtherParticipated bit=NULL,
@PAAssessmentIssues bit=NULL,
@PAForms bit=NULL,
@PAGroups bit=NULL,
@PAIFSP bit=NULL,
@PAOther bit=NULL,
@PARecreation bit=NULL,
@ParentCompletedActivity bit=NULL,
@ParentObservationsDiscussed bit=NULL,
@ParticipatedSpecify varchar(500)=NULL,
@PASpecify varchar(500)=NULL,
@PAVideo bit=NULL,
@PC1Participated bit=NULL,
@PC2Participated bit=NULL,
@PCBasicNeeds bit=NULL,
@PCChildInteraction bit=NULL,
@PCChildManagement bit=NULL,
@PCFeelings bit=NULL,
@PCOther bit=NULL,
@PCShakenBaby bit=NULL,
@PCShakenBabyVideo bit=NULL,
@PCSpecify varchar(500)=NULL,
@PCStress bit=NULL,
@ProgramFK int=NULL,
@ReviewAssessmentIssues varchar(500)=NULL,
@SiblingParticipated bit=NULL,
@SSCalendar bit=NULL,
@SSChildCare bit=NULL,
@SSEducation bit=NULL,
@SSEmployment bit=NULL,
@SSHousekeeping bit=NULL,
@SSJob bit=NULL,
@SSMoneyManagement bit=NULL,
@SSOther bit=NULL,
@SSProblemSolving bit=NULL,
@SSSpecify varchar(500)=NULL,
@SSTransportation bit=NULL,
@SupervisorObservation bit=NULL,
@TCParticipated bit=NULL,
@TotalPercentageSpent int=NULL,
@UpcomingProgramEvents bit=NULL,
@VisitLengthHour int=NULL,
@VisitLengthMinute int=NULL,
@VisitLocation char(6)=NULL,
@VisitStartTime datetime=NULL,
@VisitType char(3)=NULL)
AS
INSERT INTO HVLog(
CAChildSupport,
CAAdvocacy,
CAGoods,
CAHousing,
CALaborSupport,
CALegal,
CAOther,
CAParentRights,
CASpecify,
CATranslation,
CATransportation,
CAVisitation,
CDChildDevelopment,
CDOther,
CDSpecify,
CDToys,
CIProblems,
CIOther,
CIOtherSpecify,
Curriculum247Dads,
CurriculumBoyz2Dads,
CurriculumGrowingGreatKids,
CurriculumHelpingBabiesLearn,
CurriculumInsideOutDads,
CurriculumMomGateway,
CurriculumOther,
CurriculumOtherSpecify,
CurriculumParentsForLearning,
CurriculumPartnersHealthyBaby,
CurriculumPAT,
CurriculumPATFocusFathers,
CurriculumSanAngelo,
FatherAdvocateParticipated,
FatherFigureParticipated,
FSWFK,
GrandParentParticipated,
HCBreastFeeding,
HCChild,
HCDental,
HCFamilyPlanning,
HCFASD,
HCFeeding,
HCGeneral,
HCMedicalAdvocacy,
HCNutrition,
HCOther,
HCPrenatalCare,
HCProviders,
HCSafety,
HCSexEducation,
HCSIDS,
HCSmoking,
HCSpecify,
HVCaseFK,
HVLogCreator,
HVSupervisorParticipated,
NonPrimaryFSWParticipated,
OBPParticipated,
OtherLocationSpecify,
OtherParticipated,
PAAssessmentIssues,
PAForms,
PAGroups,
PAIFSP,
PAOther,
PARecreation,
ParentCompletedActivity,
ParentObservationsDiscussed,
ParticipatedSpecify,
PASpecify,
PAVideo,
PC1Participated,
PC2Participated,
PCBasicNeeds,
PCChildInteraction,
PCChildManagement,
PCFeelings,
PCOther,
PCShakenBaby,
PCShakenBabyVideo,
PCSpecify,
PCStress,
ProgramFK,
ReviewAssessmentIssues,
SiblingParticipated,
SSCalendar,
SSChildCare,
SSEducation,
SSEmployment,
SSHousekeeping,
SSJob,
SSMoneyManagement,
SSOther,
SSProblemSolving,
SSSpecify,
SSTransportation,
SupervisorObservation,
TCParticipated,
TotalPercentageSpent,
UpcomingProgramEvents,
VisitLengthHour,
VisitLengthMinute,
VisitLocation,
VisitStartTime,
VisitType
)
VALUES(
@CAChildSupport,
@CAAdvocacy,
@CAGoods,
@CAHousing,
@CALaborSupport,
@CALegal,
@CAOther,
@CAParentRights,
@CASpecify,
@CATranslation,
@CATransportation,
@CAVisitation,
@CDChildDevelopment,
@CDOther,
@CDSpecify,
@CDToys,
@CIProblems,
@CIOther,
@CIOtherSpecify,
@Curriculum247Dads,
@CurriculumBoyz2Dads,
@CurriculumGrowingGreatKids,
@CurriculumHelpingBabiesLearn,
@CurriculumInsideOutDads,
@CurriculumMomGateway,
@CurriculumOther,
@CurriculumOtherSpecify,
@CurriculumParentsForLearning,
@CurriculumPartnersHealthyBaby,
@CurriculumPAT,
@CurriculumPATFocusFathers,
@CurriculumSanAngelo,
@FatherAdvocateParticipated,
@FatherFigureParticipated,
@FSWFK,
@GrandParentParticipated,
@HCBreastFeeding,
@HCChild,
@HCDental,
@HCFamilyPlanning,
@HCFASD,
@HCFeeding,
@HCGeneral,
@HCMedicalAdvocacy,
@HCNutrition,
@HCOther,
@HCPrenatalCare,
@HCProviders,
@HCSafety,
@HCSexEducation,
@HCSIDS,
@HCSmoking,
@HCSpecify,
@HVCaseFK,
@HVLogCreator,
@HVSupervisorParticipated,
@NonPrimaryFSWParticipated,
@OBPParticipated,
@OtherLocationSpecify,
@OtherParticipated,
@PAAssessmentIssues,
@PAForms,
@PAGroups,
@PAIFSP,
@PAOther,
@PARecreation,
@ParentCompletedActivity,
@ParentObservationsDiscussed,
@ParticipatedSpecify,
@PASpecify,
@PAVideo,
@PC1Participated,
@PC2Participated,
@PCBasicNeeds,
@PCChildInteraction,
@PCChildManagement,
@PCFeelings,
@PCOther,
@PCShakenBaby,
@PCShakenBabyVideo,
@PCSpecify,
@PCStress,
@ProgramFK,
@ReviewAssessmentIssues,
@SiblingParticipated,
@SSCalendar,
@SSChildCare,
@SSEducation,
@SSEmployment,
@SSHousekeeping,
@SSJob,
@SSMoneyManagement,
@SSOther,
@SSProblemSolving,
@SSSpecify,
@SSTransportation,
@SupervisorObservation,
@TCParticipated,
@TotalPercentageSpent,
@UpcomingProgramEvents,
@VisitLengthHour,
@VisitLengthMinute,
@VisitLocation,
@VisitStartTime,
@VisitType
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
