SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spGetscoreASQSEbyPK]

(@scoreASQSEPK int)
AS
SET NOCOUNT ON;

SELECT * 
FROM scoreASQSE
WHERE scoreASQSEPK = @scoreASQSEPK
GO
