SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spAddPC](@BirthCountry char(30)=NULL,
@BornUSA char(1)=NULL,
@Ethnicity varchar(500)=NULL,
@Gender char(2)=NULL,
@OBP bit=NULL,
@PC1 bit=NULL,
@PC2 bit=NULL,
@PCApt varchar(200)=NULL,
@PCCellPhone char(12)=NULL,
@PCCity varchar(200)=NULL,
@PCCreator char(10)=NULL,
@PCDOB datetime=NULL,
@PCDOD datetime=NULL,
@PCEmail char(50)=NULL,
@PCEmergencyPhone char(12)=NULL,
@PCFirstName varchar(200)=NULL,
@PCLastName varchar(200)=NULL,
@PCMiddleInitial varchar(200)=NULL,
@PCNoPhone bit=NULL,
@PCOldName varchar(400)=NULL,
@PCOldName2 varchar(400)=NULL,
@PCPhone char(12)=NULL,
@PCPK_old int=NULL,
@PCState char(2)=NULL,
@PCStreet varchar(200)=NULL,
@PCZip varchar(200)=NULL,
@Race char(2)=NULL,
@RaceSpecify varchar(500)=NULL,
@SSNo varchar(200)=NULL,
@TimesMoved int=NULL,
@YearArriveUSA numeric(4, 0)=NULL,
@CP bit=NULL)
AS
INSERT INTO PC(
BirthCountry,
BornUSA,
Ethnicity,
Gender,
OBP,
PC1,
PC2,
PCApt,
PCCellPhone,
PCCity,
PCCreator,
PCDOB,
PCDOD,
PCEmail,
PCEmergencyPhone,
PCFirstName,
PCLastName,
PCMiddleInitial,
PCNoPhone,
PCOldName,
PCOldName2,
PCPhone,
PCPK_old,
PCState,
PCStreet,
PCZip,
Race,
RaceSpecify,
SSNo,
TimesMoved,
YearArriveUSA,
CP
)
VALUES(
@BirthCountry,
@BornUSA,
@Ethnicity,
@Gender,
@OBP,
@PC1,
@PC2,
@PCApt,
@PCCellPhone,
@PCCity,
@PCCreator,
@PCDOB,
@PCDOD,
@PCEmail,
@PCEmergencyPhone,
@PCFirstName,
@PCLastName,
@PCMiddleInitial,
@PCNoPhone,
@PCOldName,
@PCOldName2,
@PCPhone,
@PCPK_old,
@PCState,
@PCStreet,
@PCZip,
@Race,
@RaceSpecify,
@SSNo,
@TimesMoved,
@YearArriveUSA,
@CP
)

SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY]
GO
