SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spEditPreintake](@PreintakePK int=NULL,
@CaseStatus char(2)=NULL,
@DischargeReason char(2)=NULL,
@DischargeReasonSpecify varchar(500)=NULL,
@DischargeSafetyReason char(2)=NULL,
@DischargeSafetyReasonDV bit=NULL,
@DischargeSafetyReasonMH bit=NULL,
@DischargeSafetyReasonOther bit=NULL,
@DischargeSafetyReasonSA bit=NULL,
@DischargeSafetyReasonSpecify varchar(500)=NULL,
@HVCaseFK int=NULL,
@KempeFK int=NULL,
@PIActivitySpecify varchar(500)=NULL,
@PICall2Parent int=NULL,
@PICallFromParent int=NULL,
@PICaseReview int=NULL,
@PIDate datetime=NULL,
@PIEditor char(10)=NULL,
@PIFSWFK int=NULL,
@PIGift int=NULL,
@PIOtherActivity int=NULL,
@PIOtherHVProgram int=NULL,
@PIParent2Office int=NULL,
@PIParentLetter int=NULL,
@PIProgramMaterial int=NULL,
@PIVisitAttempt int=NULL,
@PIVisitMade int=NULL,
@ProgramFK int=NULL,
@TransferredtoProgram int=NULL)
AS
UPDATE Preintake
SET 
CaseStatus = @CaseStatus, 
DischargeReason = @DischargeReason, 
DischargeReasonSpecify = @DischargeReasonSpecify, 
DischargeSafetyReason = @DischargeSafetyReason, 
DischargeSafetyReasonDV = @DischargeSafetyReasonDV, 
DischargeSafetyReasonMH = @DischargeSafetyReasonMH, 
DischargeSafetyReasonOther = @DischargeSafetyReasonOther, 
DischargeSafetyReasonSA = @DischargeSafetyReasonSA, 
DischargeSafetyReasonSpecify = @DischargeSafetyReasonSpecify, 
HVCaseFK = @HVCaseFK, 
KempeFK = @KempeFK, 
PIActivitySpecify = @PIActivitySpecify, 
PICall2Parent = @PICall2Parent, 
PICallFromParent = @PICallFromParent, 
PICaseReview = @PICaseReview, 
PIDate = @PIDate, 
PIEditor = @PIEditor, 
PIFSWFK = @PIFSWFK, 
PIGift = @PIGift, 
PIOtherActivity = @PIOtherActivity, 
PIOtherHVProgram = @PIOtherHVProgram, 
PIParent2Office = @PIParent2Office, 
PIParentLetter = @PIParentLetter, 
PIProgramMaterial = @PIProgramMaterial, 
PIVisitAttempt = @PIVisitAttempt, 
PIVisitMade = @PIVisitMade, 
ProgramFK = @ProgramFK, 
TransferredtoProgram = @TransferredtoProgram
WHERE PreintakePK = @PreintakePK
GO
