SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spGetPC1MedicalbyPK]

(@PC1MedicalPK int)
AS
SET NOCOUNT ON;

SELECT * 
FROM PC1Medical
WHERE PC1MedicalPK = @PC1MedicalPK
GO
