CREATE TABLE [dbo].[SupervisionDeleted]
(
[SupervisionDeletedPK] [int] NOT NULL IDENTITY(1, 1),
[SupervisionPK] [int] NOT NULL,
[Boundaries] [bit] NULL,
[BoundariesComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoundariesStatus] [bit] NULL,
[Caseload] [bit] NULL,
[CaseloadComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseloadStatus] [bit] NULL,
[Coaching] [bit] NULL,
[CoachingComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoachingStatus] [bit] NULL,
[CPS] [bit] NULL,
[CPSComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPSStatus] [bit] NULL,
[Curriculum] [bit] NULL,
[CurriculumComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurriculumStatus] [bit] NULL,
[FamilyReview] [bit] NULL,
[FamilyReviewComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyReviewStatus] [bit] NULL,
[FormComplete] [bit] NULL,
[ImpactOfWork] [bit] NULL,
[ImpactOfWorkComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImpactOfWorkStatus] [bit] NULL,
[ImplementTraining] [bit] NULL,
[ImplementTrainingComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImplementTrainingStatus] [bit] NULL,
[Outreach] [bit] NULL,
[OutreachComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OutreachStatus] [bit] NULL,
[Personnel] [bit] NULL,
[PersonnelComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonnelStatus] [bit] NULL,
[PIP] [bit] NULL,
[PIPComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PIPStatus] [bit] NULL,
[ProfessionalGrowth] [bit] NULL,
[ProfessionalGrowthComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProfessionalGrowthStatus] [bit] NULL,
[ProgramFK] [int] NULL,
[RecordDocumentation] [bit] NULL,
[RecordDocumentationComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordDocumentationStatus] [bit] NULL,
[Retention] [bit] NULL,
[RetentionComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetentionStatus] [bit] NULL,
[RolePlaying] [bit] NULL,
[RolePlayingComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RolePlayingStatus] [bit] NULL,
[Safety] [bit] NULL,
[SafetyComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SafetyStatus] [bit] NULL,
[SiteDocumentation] [bit] NULL,
[SiteDocumentationComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteDocumentationStatus] [bit] NULL,
[Strengths] [bit] NULL,
[StrengthsComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StrengthsStatus] [bit] NULL,
[SupervisionCreateDate] [datetime] NOT NULL,
[SupervisionCreator] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisionDate] [datetime] NOT NULL,
[SupervisionDeleteDate] [datetime] NULL,
[SupervisionDeleter] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisionEditDate] [datetime] NULL,
[SupervisionEditor] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisionEndTime] [datetime] NOT NULL,
[SupervisionHours] [int] NULL,
[SupervisionMinutes] [int] NULL,
[SupervisionNotes] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisionSessionType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisionStartTime] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorFK] [int] NOT NULL,
[SupervisorObservationAssessment] [bit] NULL,
[SupervisorObservationAssessmentComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorObservationAssessmentStatus] [bit] NULL,
[SupervisorObservationHomeVisit] [bit] NULL,
[SupervisorObservationHomeVisitComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorObservationHomeVisitStatus] [bit] NULL,
[SupervisorObservationSupervision] [bit] NULL,
[SupervisorObservationSupervisionComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupervisorObservationSupervisionStatus] [bit] NULL,
[SupportHFAModel] [bit] NULL,
[SupportHFAModelComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupportHFAModelStatus] [bit] NULL,
[TeamDevelopment] [bit] NULL,
[TeamDevelopmentComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamDevelopmentStatus] [bit] NULL,
[WorkerFK] [int] NOT NULL,
[ParticipantEmergency] [bit] NULL,
[ReasonOther] [bit] NULL,
[ReasonOtherSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShortWeek] [bit] NULL,
[StaffCourt] [bit] NULL,
[StaffFamilyEmergency] [bit] NULL,
[StaffForgot] [bit] NULL,
[StaffIll] [bit] NULL,
[StaffOnLeave] [bit] NULL,
[StaffTraining] [bit] NULL,
[StaffVacation] [bit] NULL,
[StaffOutAllWeek] [bit] NULL,
[SupervisorFamilyEmergency] [bit] NULL,
[SupervisorForgot] [bit] NULL,
[SupervisorHoliday] [bit] NULL,
[SupervisorIll] [bit] NULL,
[SupervisorTraining] [bit] NULL,
[SupervisorVacation] [bit] NULL,
[Weather] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SupervisionDeleted] ADD CONSTRAINT [PK_SupervisionDeleted] PRIMARY KEY CLUSTERED  ([SupervisionDeletedPK]) ON [PRIMARY]
GO
