CREATE TABLE [dbo].[SupervisionHomeVisitCase]
(
[SupervisionHomeVisitCasePK] [int] NOT NULL IDENTITY(1, 1),
[ActivitiesOther] [bit] NULL,
[ActivitiesOtherSpecify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActivitiesOtherStatus] [bit] NULL,
[CaseComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChallengingIssues] [bit] NULL,
[ChallengingIssuesComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChallengingIssuesStatus] [bit] NULL,
[CHEERSFeedback] [bit] NULL,
[CHEERSFeedbackComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHEERSFeedbackStatus] [bit] NULL,
[Concerns] [bit] NULL,
[ConcernsComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConcernsStatus] [bit] NULL,
[Curriculum] [bit] NULL,
[CurriculumComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CurriculumStatus] [bit] NULL,
[FamilyGrievance] [bit] NULL,
[FamilyGrievanceComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyGrievanceStatus] [bit] NULL,
[FGPProgress] [bit] NULL,
[FGPProgressComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FGPProgressStatus] [bit] NULL,
[HVCaseFK] [int] NOT NULL,
[HVCulturalSensitivity] [bit] NULL,
[HVCulturalSensitivityComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVCulturalSensitivityStatus] [bit] NULL,
[HVHomeVisitRate] [bit] NULL,
[HVHomeVisitRateComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVHomeVisitRateStatus] [bit] NULL,
[HVReferralSources] [bit] NULL,
[HVReferralSourcesComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVReferralSourcesStatus] [bit] NULL,
[LevelChange] [bit] NULL,
[LevelChangeComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LevelChangeStatus] [bit] NULL,
[Medical] [bit] NULL,
[MedicalComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicalStatus] [bit] NULL,
[ProgramFK] [int] NOT NULL,
[Successes] [bit] NULL,
[SuccessesComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuccessesStatus] [bit] NULL,
[SupervisionFK] [int] NOT NULL,
[Tools] [bit] NULL,
[ToolsComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToolsStatus] [bit] NULL,
[TransitionPlanning] [bit] NULL,
[TransitionPlanningComments] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransitionPlanningStatus] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SupervisionHomeVisitCase] ADD CONSTRAINT [PK_SupervisionHomeVisitCase] PRIMARY KEY CLUSTERED  ([SupervisionHomeVisitCasePK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SupervisionHomeVisitCase] WITH NOCHECK ADD CONSTRAINT [FK_SupervisionHomeVisitCase_SupervisionFK] FOREIGN KEY ([SupervisionFK]) REFERENCES [dbo].[Supervision] ([SupervisionPK])
GO
