CREATE TABLE [dbo].[__Temp_Retention_Rates_Main]
(
[ProgramFK] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1ID] [char] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HVCaseFK] [int] NULL,
[IntakeDate] [date] NULL,
[LastHomeVisit] [date] NULL,
[CountOfFSWs] [int] NULL,
[CountOfHomeVisits] [int] NULL,
[DischargeDate] [date] NULL,
[LevelName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeReasonCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeReason] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1AgeAtIntake] [int] NULL,
[ActiveAt3Months] [bit] NULL,
[ActiveAt6Months] [bit] NULL,
[ActiveAt12Months] [bit] NULL,
[ActiveAt18Months] [bit] NULL,
[ActiveAt24Months] [bit] NULL,
[ActiveAt36Months] [bit] NULL,
[Race] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceText] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaxParity] [int] NULL,
[MaritalStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusAtIntake] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MomScore] [int] NULL,
[DadScore] [int] NULL,
[PartnerScore] [int] NULL,
[HighestGrade] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1EducationAtIntake] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1EmploymentAtIntake] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1PrimaryLanguageAtIntake] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TCDOB] [date] NULL,
[PrenatalEnrollment] [bit] NULL,
[AlcoholAbuseAtIntake] [bit] NULL,
[SubstanceAbuseAtIntake] [bit] NULL,
[DomesticViolenceAtIntake] [bit] NULL,
[MentalIllnessAtIntake] [bit] NULL,
[DepressionAtIntake] [bit] NULL,
[MaritalStatusAtDischarge] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1EducationAtDischarge] [char] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1EmploymentAtDischarge] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlcoholAbuseAtDischarge] [bit] NULL,
[SubstanceAbuseAtDischarge] [bit] NULL,
[DomesticViolenceAtDischarge] [bit] NULL,
[MentalIllnessAtDischarge] [bit] NULL,
[DepressionAtDischarge] [bit] NULL,
[PC1TANFAtDischarge] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PC1TANFAtIntake] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConceptionDate] [date] NULL,
[ScreenDate] [date] NULL,
[KempeDate] [date] NULL,
[EffectiveKempeScore] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
